### ISSUE TITLE
Update with mixed type id got success but got fail when query 

### ISSUE THREAD

**Issue by ljwrer** [vuex-orm/vuex-orm#110]
```js
dispatch('create', {
    data: [{
      id: '1',
      checked: false
    }]
  })
getters.find(1) //  null
getters.find('1') // {id: "1", checked: false}
dispatch('update', {
  id: 1, // typeof id is number
  checked: true
})
getters.find(1) // null
getters.find('1') // {id: 1, checked: true}
```
since query with mixed type would fail,maybe it should throw a warn or error when update,
otherwise query should be success

**Comment by kiaking** [comment]
Ah, yea this could lead problems. To solve this problem, I have a plan to add more strict attributes such as `this.string()` or `this.number` instead of `this.attr()` that should convert `'1'` to `1`.

It's kinda hard to throw warn since ID can be `string`, and changing type of the id field is OK if a user wants to do that.

I think adding strict attributes is a way to go here.

**Comment by razvanioan** [comment]
they have to be taken into account in both: getters & setters, just for consistency

I just hit this issue when I default numbers in models using ... numbers, but updating them into forms converts them into strings and this breaks filtering and stuff ...

**Comment by kiaking** [comment]
Started implementing this at #140 🏗

**Comment by kiaking** [comment]
This is now possible with Vuex ORM 0.24.3 🎉 
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.24.3
