### ISSUE TITLE
Issue trying to remove a relationship on a many-to-many

### ISSUE THREAD

**Issue by DennisOng** [vuex-orm/vuex-orm#122]
Hi, not sure if this is an expected behaviour or a bug, but there seems to be an issue with removing a many-to-many relationship.

Scenario: User has a many-to-many relationsthip to Role, similar to the case in the documentation

Initial State
```
roleUsers
{
    1_1:{
         'id': 1_1
         'user_id': 1
         'role_id': 1
    }
}
```

Trying to 'insertOrUpdate' the user with the role removed
```
const object = {
   'id': 1,
   'roles': []
}
dispatch('entities/users/insertOrUpdate', object)
```

Expected: The single entry within roleUsers to be removed

What's happening: Relationship still exists

**Comment by kiaking** [comment]
Ah, yeah, this is kinda intended I guess. However, this is an interesting situation. I think we should find some solution here but not sure if the pivot table should be removed in this case.

Because I think we don't want to remove related records in other relationship such as `hasOne`.

```js
const user = {
  id: 1,
  phone: null // <- Relation to the Phone.
}

// We don't want remove Phone record with this do we?
store.dispatch('entities/users/insert', { data: user })
```

State within Vuex ORM is temporary; if there isn't a record, it doesn't mean there isn't on the server side. There is a good chance that it isn't just being fetched yet. And we can't be sure that the server will always return full data either. Maybe on some API, the server returns all of the `roles`, and in some API, maybe the server returns only a few roles. In such case, I think we should keep the `roles` that are already fetched.

But, I do think there should be some easy way to handle this case. What I can think of currently is to add an option for removing relationship.

```js
// Delete corresponding relationship specified at `delete` if it's
// not present at `data` object.
store.dispatch('entities/users/insertOrUpdate', {
  data: { id: 1, [] },
  deleteMissingRelation: ['roles']
})
```

I haven't thought this through yet. I think we should be little more careful on how to handle this case before we do something about it...

So, for now, please workaround this issue by deleting the pivot record manually until we find some good solution for this issue.

```js
const object = object = {
   'id': 1,
   'roles': []
}

store.dispatch('entities/users/insertOrUpdate', object)

store.dispatch('entities/roleUsers/delete', roleUser => roleUser.user_id === object.id)
```

**Comment by DennisOng** [comment]
Hmm interesting one...

For the first example you gave 
```
// We don't want remove Phone record with this do we?
```
In fact in our case, we would like to remove the relationship to the phone if the 'phone' key is null. (Just the relationship, not the phone entity itself). So if a key is provided we would take that as the full data for the relationship. On the other hand, if the key is missing they we would not update the relationship.

However, l agree there might be other use cases where this behaviour is not the case, and your proposed option to delete relationship seems good. Otherwise, since this seems more a project level decision, might be worth adding 'deleteMissingRelation = true' as a config when initializing vuexORM ?

**Comment by kiaking** [comment]
To be more flexible on this issue, maybe at first step, this can be solved by incrementing the lifecycle hook like `onCreated`.

Because when we think about ordinally DB, if you remove a record, all references to that record won't be deleted unless you (the user) set up an FK constraint and cascade.

So in your example, even outside the ORM, if you try to reinsert a user with the same old ID, you would still have the same 'role' attached.

While having an option like `deleteMissingRelation` could be convenient, it might lead to unexpected result because, it's not so clear if that missing record should be deleted, or only the relation should be deleted (set the foreign key to be null?). 

By implementing lifecycle hook, users can then construct whatever behavior they wish when inserting records.

**Comment by DennisOng** [comment]
Great idea for a first step. Having lifecycle hooks/model events would give flexibility including for this case. I wouldn't think it's a blocker now since it can be easily worked around, but definitely will be a nice addition :)

**Comment by kiaking** [comment]
Great. OK, let's start implementing hooks then. It is in roadmap for version 1.0.0 too 🚀

**Comment by kiaking** [comment]
I've started implementing lifecycle hook at #133 🎉  Still might take a bit of time but I think you can see the idea.

**Comment by kiaking** [comment]
OK, I think this issue can be closed now since the lifecycle hook is implemented. Please feel free to reopen, or create another issue if you have any other trouble! Thank you so much for your feedback 🚀

**Comment by davidsandoz** [comment]
@kiaking Would there be somewhere an example of how to use a lifecycle hook to remove the relation while not deleting the related record?

The `deleteMissingRelation` option mentioned above would have been perfect for my use case, but I couldn't wrap my head around doing it with a lifecycle hook.

It looks like #185 was about doing the same thing, but the lifecycle hook solution was suggested there. Having to manually delete the relation in the pivot table is quite cumbersome.

Or is there now an easier way to accomplish this?

**Comment by kiaking** [comment]
Yeah I know, we should have some way to delete relationships in one shot as well. It just I haven't had time just yet!

**Comment by lenormf** [comment]
Be nice to have something more convenient than deleting pivot records manually.
