### ISSUE TITLE
Implement action to create a fresh record with default values.

### ISSUE THREAD

**Issue by phortx** [vuex-orm/vuex-orm#143]
```javascript
const post = await Post.dispatch('create', { data: {} });
console.log(post);    // => null
```

I've expected, that this creates a post with the default attribute values. But it seems I have to pass at least one attribute in the data object.

For me this is a bug. What do you think?

**Comment by kiaking** [comment]
This is expected at the moment. It not only doesn't create default record, but it will delete all record in the state when passing empty object to the `create` action. So it acts almost as same as `deleteAll` action.

This is kinda useful when you want to just simply sync backend state and frontend, because you can just pass any kind of response to the `create` action and the state will be refreshed.

However, maybe we could introduce another method like `new` or `make` maybe? To create fresh record with all default value?

```js
const post = await store.dispatch('entities/posts/new')
```

**Comment by phortx** [comment]
Ah ok, nice to know. This feels like a trap actually. But if it's intended and documented, it's ok I think.

A new action would be nice! :)

Thanks for your fast answer, Kia.

**Comment by kiaking** [comment]
OK, let's implement `new` then! 🔥

**Comment by kiaking** [comment]
Or one thing I just came up with, is what if we let `create` method create a new fresh record if no payload is passed. It works like `new` but with same API.

```js
store.dispatch('entities/users/create')
```

**Comment by phortx** [comment]
Some background: I have a nice `crud-page` component which auto generated a page with a data table, loads records, let's me edit them, create them, delete them, look at them and stuff.

This crud-page just gets the model class as param, so it can't know what properties this model has. When it should create a record in an abstract way, I simply can't pass anything. Looks like this:

```javascript
const record = await this.model.dispatch('create', { data: {} });
```

And then record is null, which is bad. Currently I pass `id: 9999` but that feels even bad.

Would be nice if there is a clean way to create new records with default values without passing any value :)

**Comment by kiaking** [comment]
Yeah, how about the no argument idea?

```js
store.dispatch('entities/users/create')
```

Or maybe we should have `new` method. Or even both,

**Comment by phortx** [comment]
+1 for the `new` action, because it's the same Rails ActiveRecord (and maybe other AR implementations) works :)

**Comment by dtkahl** [comment]
A `new` method which creates a new model instance without adding this instance to the vuex state would be really helpful.

I wrote a workaround method for my model classes:

```
static getFieldDefaults() {
    return Object.entries(this.fields()).reduce((result, [name, field]) => {
        result[name] = field.value;
        return result;
    }, {});
}
```

**Comment by kiaking** [comment]
@dtkahl Hah, maybe you could do that with `const user = new User({ ... })` ? Or you could do `const user = User.make({ ... })` too I think. To get the model instance without saving it to the store. It will not normalize the given object though...

**Comment by dtkahl** [comment]
Yes, that works.

**Comment by kiaking** [comment]
Changing the issue title to implement `new` method!

**Comment by kiaking** [comment]
The `new` method has arrived at Vuex ORM 0.28.0! 🎉 
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.28.0

**Comment by dantodev** [comment]
Hi @kiaking, Since 0.27.0 the `make` method is missing on the model instance. You suggested me to use this one. Is there any replacement? The `new` Method is not doing the same thing. I want to get a Model instance with default Values without persisting it to the store. 

the `make` method internally used a method called `fill` which is gone as well. But there is also the method `$fill` could this be used as replacement? I cant find any documentation for this method in the docs.

**Comment by kiaking** [comment]
@dantodev Hi! Sorry for many confusion here. Yes, you can use $fill, but it's pretty much same as doing `new User({ ... })`. Would this work for you?

**Comment by dantodev** [comment]
If this results in creating a model instance without storing an empty model to the store this would work for me.

**Comment by kiaking** [comment]
@dantodev Yes, that is what it does. It will create a model instance, but it will not store them to the store.
