### ISSUE TITLE
Loading the same related models in multiple relationships merges them

### ISSUE THREAD

**Issue by UncertaintyP** [vuex-orm/vuex-orm#155]
In this [jsfiddle](https://jsfiddle.net/c17neocb/) I have created a `Location` model that has many `Event` models.

One relation is called `past` the other `upcoming`. Loading both of them or loading them separately returns all 5 events (past as well as upcoming) on the respective locations property.

But having a look at the state of the store reveals it has the correct values.
![screenshot from 2018-05-12 15-08-03](https://user-images.githubusercontent.com/13165602/39957628-5be1d854-55f6-11e8-9431-16149355e6c5.png)

**Comment by kiaking** [comment]
Oh well, this is expected behavior right now.

Since `past` and `upcoming` attribute defined at `Location` class is referencing same `Event` model and same foreign key `localtion_id`, when fetching data from the state, the result is going to be the same hence you get all 5 events back.

`past` and `upcoming` property in the state you posted (`locations`) are indeed the ID of the related items, but Vuex ORM will not reference those to fetch data, it looks for the foreign key (`location_id` by `id` of `Location`).

My recommendation is to make `Past` and `Upcoming` a separate Model, but also you could use `hasManyBy` relationship.

```js
// Models
class Location extends VuexORM.Model {
    static entity = 'locations';

    static fields () {
        return {
            id: this.increment(),
            name: this.attr(''),
            past: this.hasManyBy(Event, 'past'),
            upcoming: this.hasManyBy(Event, 'upcoming'),
        }
    }
}
```

The `hasManyBy` relationship will look for the specified field's array and fetch data (in the above example it's `past` and `upcoming` field).

**Comment by UncertaintyP** [comment]
Thanks for the clarification, I just didn't expect it to work this way but `hasManyBy` is totally what I'm looking for.

Your recommendation of creating multiple models is no option for me as the location -> past/upcoming relation was just one of many examples in my app that have this problem and I wanna keep the models folder slim ... `hasManyBy` is just cleaner ;-)

**Comment by kiaking** [comment]
Glad it worked for you! Let me know if you face any other trouble 👍
