### ISSUE TITLE
Circular dependency problem when using hasMany/belongsTo

### ISSUE THREAD

**Issue by siegy22** [vuex-orm/vuex-orm#160]
I have the following problem:

Let's assume I have comments which belong to a user, and a user who has many comments.
How do I define `belongsTo` on the Comment, as well as `hasMany` on the User?

```javascript
class Comment extends Model {
  static entity = 'comments'

  static fields() {
    return {
      id: this.attr(null),
      body: this.attr(''),
      user_id: this.attr(''),
      post: this.belongsTo(User, 'user_id'),
    }
  }
}

class User extends Model {
  static entity = 'users'

  static fields() {
    return {
      id: this.attr(null),
      name: this.attr(''),
      comments: this.hasMany(Comment, 'user_id')
    }
  }
}
```

So with this example you'll have a lookup error when defining `belongsTo` in the Comment class.
If you split these two in two separate files, you will result in a circular dependency.

How do I solve this?

**Comment by kiaking** [comment]
This is kinda bundler related issue. For example, not sure why but the example you gave me works fine with my setup. It doesn't throw any error. In fact the exact same setup is defined at almost everywhere at Vuex ORM test cases. I'm thinking this because the `fields` is method, and it is evaluated on the run time.

However, if you wish, you can actually use String to define relationship 😃 

```js
class Comment extends Model {
  static entity = 'comments'

  static fields() {
    return {
      id: this.attr(null),
      body: this.attr(''),
      user_id: this.attr(''),
      post: this.belongsTo('users', 'user_id'),
    }
  }
}

class User extends Model {
  static entity = 'users'

  static fields() {
    return {
      id: this.attr(null),
      name: this.attr(''),
      comments: this.hasMany('comments', 'user_id')
    }
  }
}
```

Remember to use the entity name for the class, not the class name 👍

**Comment by kiaking** [comment]
@siegy22 Hi! Did the above answer solve your issue? I would like to close this issue if there're no further questions : )

**Comment by siegy22** [comment]
Yes it did!

I forgot to add `with('post')` when I added `post: this.belongsTo('users', 'user_id'),`. So I already tried that 😄

**Comment by kiaking** [comment]
Great you found a fix! No it is not documented yet and I should! I wasn't quite sure if I wanted to go with using String as a argument since I didn't had circular problem until you raised the issue. (I did implement the string feature because I thought maybe the circular might become an issue though). So yeah I should add it!
