### ISSUE TITLE
Async lifecycle hooks?

### ISSUE THREAD

**Issue by mattrothenberg** [vuex-orm/vuex-orm#178]
Hello!

I've noticed that when using `async` with my lifecycle hooks, the data is stored in Vuex incorrectly as a promise.

```js
async beforeCreate(context, record) {
  console.log(record);
}
```
![screen shot 2018-06-28 at 10 48 49 am](https://user-images.githubusercontent.com/5148596/42041892-de79b888-7ac0-11e8-8510-d55a0fae6bf1.png)

My use case is that I want to persist these records asynchronously (to my backend) after they're created on the client side. Is there a preferred and/or different way of doing so?

Thanks for creating/supporting this awesome library!

**Comment by kiaking** [comment]
Hi! Thank you for the feedback! Yes, unfortunately, Promise (async) is not supported by the lifecycle at the moment. 

> My use case is that I want to persist these records asynchronously (to my backend) after they're created on the client side. Is there a preferred and/or different way of doing so?

If you need to process the record *after* they are created, could you try using `afterCreate` instead of `beforeCreate`. Then I think it should work fine.

**Comment by Tofandel** [comment]
Mmm.. The beforeCreate Lifecycle hook should really support async, because you HAVE TO (no other way around) use it to insert pivot records that have composite primary keys..

And the problem is that the insertOrUpdate is in itself async.. So if you don't wait for the data to be inserted you run into race conditions...
