### ISSUE TITLE
Backend API plugin discussion

### ISSUE THREAD

**Issue by kiaking** [vuex-orm/vuex-orm#200]
Issue continuing from https://github.com/vuex-orm/vuex-orm-graphql/issues/39.

Related Issue: #44

Let's see how it goes with the API design!

/cc @phortx @madmike

**Comment by rkingon** [comment]
I just started following the old thread, I created a (very quick) Axios HTTP implementation by creating a plugin that extends `Actions`.

I am happy to clean it up a little and share, it appears to work great. (I haven't done destroy yet since I haven't needed it on this project.)

Also, there is a library I previously used called `js-data` that was pretty nice. The way they implemented adapters was great- especially since sometimes you need to interact with more than HTTP. On one project I use a mixture of sockets.io & HTTP. 

Here is a link to their adapter section for reference/ideas:
http://www.js-data.io/v3.0/docs/js-data-adapter

**Comment by phortx** [comment]
> Also, there is a library I previously used called js-data that was pretty nice. 

I've used that too, but had some serious trouble with js-data, but I really loved the adapter pattern too.

I think we should first make clear whether we seperate persistence and vuex actions or not. js-data doesn't that as far as I know.

**Comment by madmike** [comment]
Hello! Nice to hear from you all here again!
As I've already told it would be great to have some kind of "clever" logic which would analyze settings and adapter had been installed - call persist method too. So it appeared that there is a problem with reactivity? Maybe try somehow to solve this issue?
Because splitting api on 2 or even 3 layers can seem a bit complicated. If you develop some project which needs to persist almost everything - you have to call two methods each time you run any operation.
As i've said i was looking for some js library which can handle the client part of JSON API format and found out the nice lib - JSORM. Can take a look at it.

**Comment by phortx** [comment]
I understand the wanting of having just one layer. I was on this train too very long. 

Splitting in two layers are what I currently doing in the GraphQL Plugin and it works out very well. Because retrieving from the store and retrieving from the server happen in different stages of the component lifecycle.

Let's look at this vue container component

```
<template>
  <div>
    <loading-spinner v-if="!loading" />
    <product-card v-for="product in products" :model="product" v-else />
  </div>
</template>

<script>
  import Product from 'data/models/product';

  export default {
    name: 'product-list',
    data() {
      return { loading: true };
    },
    computed: {
      product: () => Product.findAll();
    },
   async created() {
     await Product.fetch();
     this.loading = false;
   }
  }
</script>
```

This is a simple component like we have dozens of. Let's assume the `findAll()` also does the fetch. Following questions come to my mind:

- Is the reactivity still given? (I think @kiaking can answer this).
- How to you handle cache invalidation? How can the developer force a reload of the record? How can we be sure that the record isn't deprecated?
- What happens if have a record only on client side (just created it) and we're calling `find()`. How does the system know that it shouldn't fetch the record from the server?
- How can we manage the loading state with the example above?

Also I think the merging of the both layers (persistence and state) will cause the developer to think less of the distinction between Vuex Store and Server. There are cases where we don't run CRUD operations against the server and then custom requests are necessary. (In Vuex-ORM-GraphQL there are custom mutations/queries and simple mutations/queries for this reason, just take a look in the docs). This forces the developer to think about persistence. So sometimes the developer has to care about persistence and sometimes not, this feels not so elegant.

Also I want to quote @kiaking from our original discussion about separating persistence and state or not (see #44):

> So Vuex Store (Vuex ORM) is kinda cache. If you save data into Vuex, it is not persistent. If you refresh the browser, it goes away. And sometimes we want that! For example, many of my application need that feature. I would like to update Vuex Store so that other components update their displayed value, but don't want sync to the persistent layer (REST or GraphQL) just yet.

There was also a git comparsion: In git you can commit, branch and revert stuff as much as you want and when you feel ready, you push it to the origin. We do the same with Vuex-ORM records: We create a record, bind the properties to form fields and when the user clicks on "cancel", we just delete the record. When the user clicks on "save" we persist it to the server. This is a good practice but no longer possible when we don't have the distinction between creating and persisting a record. Without that distinction we would need all form fields bind to the component state (`data()`) and on save fill the record. This feels bloated for me.

Also from #44 and @kiaking 

> By the way, why this is so hard is because it's async. If fetching data from GraphQL could be synchronous, there's no problem at all. You don't need User.sync() method. Just hydrate data inside getters.
>
> The only way to remove User.sync() method and make everything work with single User.findAll() I can think of, is to use vue-async-computed and asyncComputed property.

Not sure if this is still an issue, but it makes sense to me: computed properties can't be async but the server requests are async. This could be difficult.

Don't get me wrong, I'm not totally against the one-layer-solution, I just want to show the issues :)

**Comment by rkingon** [comment]
100% need two methods... one to  pull from client side "already in store" (synchronous) and one to grab from whatever remote (asynchronous)

There will be many times where you need to pull from local and not want to touch the server

**Comment by madmike** [comment]
Well, sure there must be methods for pure client-side storage usage. I'm speaking about persistence methods which can handle two operations at once - create/modify/destroy local model and then at once send necessary HTTP request to api server. Such an interface seems quite intuitive to the new developer who came to such a library first time. Basically such methods as **create**, **update** and **destroy** assume to have persistence underneath, but however there can be other methods **new** (or **build**), **set_attributes**, **delete** - which will modify local object and can be persisted with save method for example. **all**, **fetch**, **find** for example - can fetch the data from server and then create local objects, but something like **filter**, **get** ... - can work only with local objects.

So this way these methods can be split as it was said into three layers but not so strictly as it was suggested:
* frontend layer methods (models in memory)
  * new(), build() - creating record in-memory
  * filter(), get() - find records/record from memory
  * set_attribute, set_attributes - update attributes of record in-memory
  * delete - delete record from memory
* combined layer (in-memory operations + syncronizing with backend), with no backend configured acts as pure front-end layer
   * create() - creating record both in memory and sending API request
   * all(), find() ... - find records from API with caching (need to have clever caching mechanism, maybe store total records number and have some options to be configured whether to always sync with server, or load from API just once)
   * update() - update record both in-memory and on API
   * destroy() - destroy record on API and delete it from memory
* pure API layer
   * sync() - maybe to update the model already fetched with all() method
   * save() - to store changes made with new() or set_attribute() methods

I see it somehow this way.

**Comment by phortx** [comment]
> I'm speaking about persistence methods which can handle two operations at once

Actuall we have exactly that: We have some methods to work with the store, some methods to sync the with the server and methods that just do both of them.

Vuex-ORM defines the store methods (create, update, delete, find, findAll)
Vuex-ORM-GraphQL as a persistence plugin defines the sync methods (persist, push, destroy, fetch) and also a set of methods that just do both: deleteAndDestroy, updateAndPush, createAndPersist, fetchAndFind (only the first one exists currently, the rest is not implemented yet).

So there is no need for any discussion here, when we all want to do exactly that :)

**Comment by madmike** [comment]
Let's say it's almost so. Just the matter of naming.
For me it would be clearer if core store methods (create, update, find and maybe add here destroy) - would be overloadable in plugins. These methods are the common convention in some server-side ORMs. And in fact these server-side ORMs have much in common with such client-side ORM. There you can build a new model in memory and work with it without persisting (for example when rendering new form) and on the other side with one create method you can build such a model and persist data to the DB. The same way you can set model attributes to the model in-memory and then with save() method persist changes to DB or you can call update() method and do these two tasks at once.

Personally i don't understand the need of deleteAndDestroy method, this logic can be done by the destroy itself. In fact I don't understand when do we need that persistence-only layer (as i wrote above i see only two methods: to persist changes - save() and something like fetch() or sync() to refresh data). If keep it just as internal set of methods and use them in that dual functions like deleteAndDestroy? This way it would be better to keep shorter names for these last ones.

In addition here we can discuss all those potential problems you @phortx wrote in the previous post. The caching mechanism, reactivity and so on.
Caching and filtering in fact is a really huge part of it all. Ideally it's worth to have some analogue of DB queries caching mechanism here and with some complex logic filter in-memory cache and with some conditions perform remote query. Or add some nice configuration options for user who can manage situations when it's enough just to search (or order)  the cache and when it's necessary to perform full DB query on the server side.

So first of all I suggest to list here the full set of methods with some description. And after that implement some common functional without caching and some complex parts which would suite the conception of plugins.

**Comment by phortx** [comment]
> Personally i don't understand the need of deleteAndDestroy method, this logic can be done by the destroy itself.

It could but I think this way we would suffer a lot of flexibility. What if you want to destroy a record on the server,  but not delete it on the client side. In this case you have to clone your record first, call `destroy()` which deletes the record on the server an then you have only one record left, but this isn't very elegant I think.

> Caching and filtering in fact is a really huge part of it all. Ideally it's worth to have some analogue of DB queries caching mechanism here and with some complex logic filter in-memory cache and with some conditions perform remote query.

Fortunately I get this from the apollo-client library and thus I don't have to care about that for Vuex-ORM-GraphQL. But we don't have this luxury for every kind of adapter we want to implement, so you're right: This will produce some headaches :D

> So first of all I suggest to list here the full set of methods with some description.

I think @kiaking has done this on the [other thread](https://github.com/vuex-orm/vuex-orm-graphql/issues/39#issuecomment-404010846) very good.

**Comment by madmike** [comment]
@kiaking wrote this table:

CRUD | Vuex Only | Backend Only | Both
-- | -- | -- | --
READ | find | fetch | get
Create | insert | persist | add
Update | update | push | edit
Delete | delete | destroy | remove

And you answered that it would be too complex.
I suggest to keep things simpler for the user. And choose the most intuitive method names to implement the functionality that is expected. As was said - **create()** - for creating record on both sides, **update()** - for updating record on both sides, **destroy()** - for destroying record on both sides. For those who don't need any backend and want to use this ORM as in-memory only (or for some exact model) - then all these methods will work as frontend only and all current functional will stay as it is.

Then for such a situation as you've described when you need to perform a remote-only operation (destroy an object on server and keep it at client side) we can add methods with longer names because these cases are quite rare. For example **remoteDestroy()**, **remoteCreate()** (really don't know would it be useful). In this layer would be sure - **save()** and **refresh()** (or **sync()**) to persist in-memory object and sync state with server.

And for frontend only operations some less popular method names but still simple - for example **init()** (or **new()**, **build()), **set_attributes()**, **delete()**.

Fetching all records, filtering and finding record by id - is more complex question as i could realise. But again i think it's possible to solve the problems with reactivity and caching. And again the same logic will work here: **all()** - fetch data from remote and create local models (or look through the cache), **getAll()** (for example) - fetch from local in-memory storage only, **find(id)** - find the record by id with some complex logic in cache or performing request to server, **get(id)** - find record in-memory cache only. Here must be some pagination methods (**page()**, **per()**), sorting (**order_by()**) and so on.

I think such convention will be clear for the newcomers.

**Comment by madmike** [comment]
I used this code when was playing around with JSORM library and it works well:
```javascript
<template>
  <section id="main" class="row">
    <sidebar :categories="categories" class="sidebar col-3" />
  </section>
</template>

<script lang="ts">
  import Sidebar from "~/components/sidebar.vue"
  import { Category } from "~/models/category"

  export default {
    components: { Sidebar },
    async asyncData (context) {
      let { data } = await Category.all()
      return { categories }
    }
  }
</script>
```

**Comment by bradstewart** [comment]
I've been using a solution similar to @rkingon 's, except I'm just adding actions to the store modules at registration time rather than using a VuexORM plugin (simply because it was an easier integration with existing code).

I prefixed all of the action names with "api" to make it painfully obvious when things would hit the network or not. The abridged version:

```ts
function createStoreModule <T extends typeof Model> (entityType: T, options = {}) {
  const baseURL = `/api/v1/${Inflector.tableize(entityType.entity)}`

  function url (id?: string) {
    return id
      ? `${baseURL}/${id}`
      : baseURL
  }

  const baseModule: Vuex.Module<any, any> = {
    actions: {
      async ['api/fetch'] ({ dispatch }, recordOrId) {
        const { data } = await HTTP.get(url(getId(recordOrId)))

        return dispatch('insertOrUpdate', {
          data,
        })
      },

      async ['api/fetchAll'] ({ dispatch }) {
        const { data } = await HTTP.get(url())

        return dispatch('insertOrUpdate', {
          data,
        })
      },

      async ['api/create'] ({ dispatch }, record) {
        // If we have a real VuexORM Model instance, serialize it first.
        if ('$toJson' in record) {
          record = record.$toJson()
        }

        const { data } = await HTTP.post(url(), record)

        return dispatch('insertOrUpdate', {
          data,
        })
      },

      async ['api/update'] ({ dispatch }, record) {
        // If we have a real VuexORM Model instance, serialize it first.
        if ('$toJson' in record) {
          record = record.$toJson()
        }

        const { data } = await HTTP.patch(url(record.id), record)

        return dispatch('insertOrUpdate', {
          data,
        })
      },

      async ['api/destroy'] ({ dispatch }, recordOrId) {
        const { data } = await HTTP.delete(url(getId(recordOrId)))

        return dispatch('delete', data.id)
      },
    },
  }

  return merge(baseModule, options)
}
```

It's by no means super flexible (or robust outside of my specific use cases), but it works well.

**Comment by kiaking** [comment]
@KaniRobinson has created [Vuex ORM Axios](https://github.com/vuex-orm/plugin-axios) plugin! So, lets create issues and PRs over there to make the library better : )

**Comment by rkingon** [comment]
sweet! looks pretty cool, I have a couple projects I can try swapping it out on.

**Comment by kiaking** [comment]
@rkingon There's more work needed! Feedback will be super welcome!
