### ISSUE TITLE
Enhancement: Query caching

### ISSUE THREAD

**Issue by clockworked247** [vuex-orm/vuex-orm#215]
Hi @kiaking,

Thanks so much for your great library.  I've benefited so much from its existence.

I'd like to make a proposal for an enhancement that I'd be happy to implement: Query Caching.

If the particular part of the Store that you're querying has not changed since your last query, the query should return a cached result rather than perform another lookup across normalized data.

Would this be something you'd be interested in me working on for the 1.0 release?

**Comment by kiaking** [comment]
Thank you so much for the wonderful proposal! Yes, it would be super nice to have caching feature and would be awesome if you can work on!

Not sure how much it would relate to the implementation for this feature, but I would like to note the fundamental architecture improvement we're planning right now. It is about issue #163.

That is the long thread but simply put, what we are trying to do is;

1. Save model instance directly to the store. Currently, Vuex ORM saves plain records to the store and instantiate the model each time getters are called, but we're trying to change this. This is planned to be implemented before version 1.0.0.

2. Create an index map of the relation and reference it instead of creating a whole new model instance. This is planned to be implemented after version 1.0.0.

Even though the above features are implemented, the caching feature still has benefited because the above feature wouldn't cache for example `where` condition.

Please let me know if you have any questions about those features! And again, thank you so much for the proposal!

**Comment by clockworked247** [comment]
@kiaking Thanks for the info on what changes are going into 1.0.0.  I'll look them over and come up with a proposal.
