### ISSUE TITLE
orderBy and computed value

### ISSUE THREAD

**Issue by drkwolf** [vuex-orm/vuex-orm#233]
is there a way to use order by with model's computed (getter) value ?

**Comment by kiaking** [comment]
Hi! Not 100% sure what you mean but you could do this?

```js
class User extends Model {
  // ...
  
  static get orderByAge () {
    return this.query().orderBy('age')
  }
}

User.orderByAge.get()
```

**Comment by kiaking** [comment]
Thank you for the response! But, I'm still not sure if I'm understanding your question correctly... Your example looks pretty good and it should work fine... right?

Could you elaborate bit more about what problem you are trying to solve? 😢

**Comment by drkwolf** [comment]
thank you for your interest !
 
first OrderBy gives wrong result with the above code
```javascript
getters['entities/invoices/query']().with('items').orderBy('total_amount', 'asc').get().map(e => e.total_amount)
   
(46) [20, 30, 30, 20, 30, 40, 40, 30, 20, 20, 40, 20, 40, 40, 20, 30, 20, 20, 30, 30, 30, 20, 30, 40, 30, 40, 30, 30, 30, 30, 20, 30, 20, 40, 20, 20, 40, 40, 40, 40, 30000, 1, 1, 1, 20001, 1400] 
```
* you can see that orderby doesn't perform as it should
 * trying the same code without orderBy gives the same result 
``` Javascript
getters['entities/invoices/query']().with('items').get().map(e => e.total_amount)

(46) [20, 30, 30, 20, 30, 40, 40, 30, 20, 20, 40, 20, 40, 40, 20, 30, 20, 20, 30, 30, 30, 20, 30, 40, 30, 40, 30, 30, 30, 30, 20, 30, 20, 40, 20, 20, 40, 40, 40, 40, 30000, 1, 1, 1, 20001, 1400]
```
* the output values are correct, but the order are not. it seems orderBy ignore computed values

* after modifying the code  (adding setter, and amount value to static fields), orderBy works (but it's not perfect. see below) 
````javascript
class Invoice extends Model {
  static entity = "invoices";
  static fields() {
    return {
      ....
    total_amount: this.number(), // here
      items: this.hasMany(InvoiceItem, "invoice_id")
    };
  }
set total_amount(valu) {} // and here
  get total_amount() {
    return this.items.reduce((amount, item) => {
      return amount + item.total
    }, 0)
  }
}
````
* the order is working:

```` javascript
getters['entities/invoices/query']().with('items').get().map(e => e.total_amount)
   
(46) ) [ 1, 1, 1, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 1400, 20001, 30000]
````
I don't exactly know why this works ( is the  value of total_amount cached at the insertion ?)

* but i still got the same problem after updating or inserting new record

```javascript 
// insert 
getters['entities/invoices/query']().with('items').orderBy('total_amount', 'asc').get().map(e => e.total_amount)
   
(47) [6000, 1, 1, 1, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 1400, 20001, 30000]

//update
(47) [6000, 1, 1, 1, 20, 2, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 1400, 20001, 30000]
````

**Comment by RickMeijer** [comment]
I'm having a similar issue. Trying to sort on the number of unread `hasMany.Messages` of a `User`. 
Right now I'm sorting after the fact, since any computed parameter seems to be unavailable in a query(?). The fuzzy search also can't reach computed relationship properties.

I'm guessing 
> Currently, Vuex ORM is instantiating models from records when fething them via getters. 
(via #231 ) is part of the problem. If the Models are instantiated on a get, the computed values are unreachable since it doesn't have a Model attached to it yet. But this is pure conjecture on my part.

**Comment by kiaking** [comment]
@drkwolf Ohhhh OK, finally I got it. Yes, as @RickMeijer explained, you can't use computed property in orderBy method at the moment.

But, however, I'm currently implementing issue #234, and once this is done, you will be able to use computed property inside any query filters including orderBy 👍 

I don't think it would take long before I can release the new version, so stay tuned! (and sorry for the inconvenience right now

**Comment by RickMeijer** [comment]
So I made [this awesome demo](https://codesandbox.io/s/6njo77oy7k) to help explain for naught? The horror! Anyways; good stuff, thanks. A work in progress should never be a problem as long as it's _work_ and _in progress_ (R.R. Martin/Patrick Rothfuss I'm looking at you.).

**Comment by kiaking** [comment]
Vuex ORM 0.27.0 is released! 🎉  Now you should be able to use computed value in order by : ) Again, thank you so much for the report, and thank you for your demo @RickMeijer ;)
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.27.0

**Comment by RickMeijer** [comment]
For the people in the future coming in from Google:
When I update the demo to 0.27, I don't see any changes on the sorting for relational data.
It seems like relational data isn't available before the data is retrieved, so orderBy a computed property only works if the computed property references the Models' own properties.
@kiaking  says as much in #231: 
> However, we must recreate models when fetching records with relationships since Vuex State cannot be modified outside of mutation handler.

Correct me if I'm wrong though.

And since a post wouldn't be complete without a small playground to test in: https://codesandbox.io/s/6njo77oy7k

**Comment by kiaking** [comment]
@RickMeijer Ahhh good point. Yeah the property that refers to relationship, you can't do that. I wonder how other ORMs handles this.Maybe we could have this as a feature request if it's possible.

**Comment by drkwolf** [comment]
hi,  the proposed fix doesn't work in my case, since my computed property depends on a relationship.

the problem here is that orderBy is executed before eagerLoading, loading the relationship inside the computed value is quick and dirty fix, i've made a working example (based on @RickMeijer example)  here https://codesandbox.io/s/lpz62qz8jz that expose the problem

**Comment by kiaking** [comment]
@drkwolf Yeah, in that case, you need to filter the result after the `get` call I guess. I wonder if there's a way to do this in other ORM's. I'm curious how would the API look like 🤔 

I think it's not a good way to resolve relationship before the `where` clause because that is going to impact performance a lot.
