### ISSUE TITLE
0.27: Direct store mutation through model

### ISSUE THREAD

**Issue by kpilard** [vuex-orm/vuex-orm#237]
Hey,

I am not sure if this is a mistake or if we used the library incorrectly:

Our concept:
 - load Data in the Store
 - receive a model instance by id
 - change some values (e.g. `model.name = 'newName'`)
 - call our custom save Method in the Model
 => The save Method will make an API-Request. On success the new data will saved in the store.

This was possible because the getter created new instances of the model. Now, however, the object is returned directly from the store. As a result, the store is unfortunately mutated directly (without an mutation).

If you have an store with activated strict mode (https://vuex.vuejs.org/guide/strict.html) you will get the following error: `Do not mutate vuex store state outside mutation handlers.`

Unfortunately I do not know if you want to support this use case. 
But tickets like this at least indicate that. https://github.com/vuex-orm/vuex-orm/issues/150

**Comment by kiaking** [comment]
Hi! Thank you for the report!

Yes, this behavior is intended at 0.27.0. I know it was possible to mutate the retrieved records before 0.27.0, but I never wanted to recommend such usage.

Since Vuex ORM is just a Vuex plugin, mutating the value returned from getters should be considered as an anti-pattern.

I understand what you're trying to do, but I think it should be supported in a different way, such as creating temporary "workspace" store state. Mutating the object returned from getters may cause some unwanted result regarding the reactivity system as well.

You are also right about "save" method - #150 -, but that method is more intended to be used something like follows (user object is not created inside Vuex Store).

```js
export default {
  data () {
    return {
      user: new User()
    }
  },

  methods: {
    save () {
      this.user.$save()
    }
  }
}
```

Maybe we could add some option or method to get a fresh instance from getters. I see some use case for that. But again, I'm not sure if we really want to take that path as we're using Vuex under the food.

What do you think?

**Comment by kpilard** [comment]
> Since Vuex ORM is just a Vuex plugin, mutating the value returned from getters should be considered as an anti-pattern.

Yes, you are absolutely right. 
Before we used this library, we cloned the data to fill our forms. We should do that now too.
Thanks for the response ;)

**Comment by kiaking** [comment]
Thanks for your kind understanding! Please feel free to open another issue if you have any trouble!

**Comment by SzNagyMisu** [comment]
I bumped into this issue recently, and I am not sure I understand all the reasons.

We wanted to use this package the following way:
* get a copy of the record in the vuex store by a getter
* mutate the properties of this copy by `v-model` in the forms
* save the changes to the vuex store at a given point

The funny thing it kinda worked as long as we used queries like `User.query().with('roles').all()` - the important part being `with()`. This is because [Query.ts#L732](https://github.com/vuex-orm/vuex-orm/blob/150a01a0dc37d29b2f1e30cabe68a12f543a01ba/src/query/Query.ts#L732) re-initializes the model instances if `load` property is not empty (is filled by `with()`). But recently we had a rare case, when no relations were needed, and we bumped into vuex's error.

So, the point is, we **do not intend to mutate** the vuex store state outside mutations, but mutate the copy, and save the changes via mutations.

Furthermore I think the behaviour is inconsistent, since it works makes copies when `with()` is used, but without it a workaround is needed (like `new User(User.find(1))` or `User.query().with('').find(1)`)

@kiaking what do you think about it?

Thanks in advance!

**Comment by kiaking** [comment]
@SzNagyMisu Hi! Yeah, the getter will return a new copy of Model when you fetch them with a relationship. This is by design.

I agree that the behavior is inconsistent, but I made it like so to gain a bit of performance when you don't need relationships. Furthermore, it is going to be essential to return the state as is when we implement lazy loading.

Maybe it's a bit opinionated, but I strongly don't recommend trying to mutate the value returned from the getter. I understand you're not trying to mutate them, but I think copying the object should be done inside Vue Component rather than in Getters. Because getters a like computed property in Vue Component, and I think it's a kinda anti-pattern to mutate the value you get from the computed property.

But, I still understand your case too. So I'm kinda open on idea to have another API that explicitly tells Vuex ORM to fetch a copy of models. What do you think?

**Comment by SzNagyMisu** [comment]
Hi @kiaking 
I see your point about mutating the value recieved from a getter being an anti-pattern. In order to understand my point of view I tell you my story:

Just before we found `vuex-orm`, I have been reading a [Vue forum discussion](https://forum.vuejs.org/t/vuex-best-practices-for-complex-objects/10143) about storing data in `vuex`, where LinusBorg advised two important things:
1. to [normalize data](https://forum.vuejs.org/t/vuex-best-practices-for-complex-objects/10143/2) (this is done well in `vuex-orm`)
2. to [store only plain objects](https://forum.vuejs.org/t/vuex-best-practices-for-complex-objects/10143/4) in `vuex`

So, after that, when we found your plugin, I assumed it is built upon those priciples, I was sure that the data stored in `vuex` is **normalized** and **converted to plain objects**. I thought it worked like the `getters` returned the plain object, and the model methods converted them to instances. A bit like the way [`ActiveRecord`](https://guides.rubyonrails.org/active_record_basics.html) works.
This way the principle of not mutating data from getters directly would be respected, but we would have the possibility of mutating the instance and saving it to the `store` on appropriate moments.

Now, being more familiar with the way `vuex-orm` works, I am not sure this logic can be implemented... Perhaps an option could be passed to the `install()` function indicating that I want my data not only normalized but converted to plain objects as well. But that would be hard work to implement.

Until then, I think, I will just use `new User(User.find(1))`.

**Comment by kiaking** [comment]
@SzNagyMisu Thank you for the detailed explanation! Yeah, I understand your use case.

Well, Vuex ORM actually stores Class instance directly to the Vuex Store. The reason is it's going to be a bit faster to load data because we don't have to instantiate each record every time we fetch from the store.

So I guess, as you said, we could have a new API that returns a copy of the record. Since your workaround `new User(User.find(1))` should work on most of the cases, there is a chance that records could have Object and Array, in that case, it will not work correctly. We must do a deep copy.

Something like `User.query().getNew()` could be nice...?

**Comment by SzNagyMisu** [comment]
@kiaking I like the idea of deep copying a record. Although, I'd rather prefer something like `User.find(1).$clone()` or `$deepClone()`. What do you think?

**Comment by kiaking** [comment]
@SzNagyMisu Ah, good idea! That makes much more sense. Could you open another issue for adding `$clone` method to the model?
