### ISSUE TITLE
WARN: Cannot stringify arbitrary non-POJOs

### ISSUE THREAD

**Issue by ozum** [vuex-orm/vuex-orm#255]
Hi,

I installed and run [vuex-orm/vuex-orm-examples-nuxt](https://github.com/vuex-orm/vuex-orm-examples-nuxt) and I got warnings on terminal for every page refresh:

```
 WARN  Cannot stringify arbitrary non-POJOs Todo

 WARN  Cannot stringify arbitrary non-POJOs User
```

I get same warnings in my project, which uses latest Nuxt (v.2.3.2).

Kind Regards,

**Comment by kiaking** [comment]
Hi! Thanks for the report! I have the same warning for my Nuxt project as well.

Currently, Vuex ORM will work so you can ignore warning at the moment. The reason why we're getting this warning is that we've started to store class instance directly to the store. When the store gets hydrated at server side, Nuxt try to serialize the store and fails because there's class instance inside the store (functions can't be serialized). Vuex ORM will re-instantiate the model at client side so it still works.

Now I don't know what is the right way to handle this warning. Maybe it's a bad idea to store class instances to the store and we should instantiate the record each time we fetch them (like we did before). But not sure. I would love to hear some nice idea on this.

**Comment by kiaking** [comment]
@ozum OK thanks! I'll try communicate with Nuxt guys if I can.

**Comment by ozum** [comment]
There is some info about cause of this [here](https://cmty.app/nuxt/nuxt.js/issues/c7961) but no solution.

It seems it is related to a package called `devalue`, but I don't know what it is.

**Comment by kiaking** [comment]
Yeah. I think it's going to solve this unless we make internal change to the Vuex ORM.

Basically, Nuxt is hydrating the store state, and sending it to the client as a string. Then, at the client side, it uses that hydrated store. So, the state gets serialized before the store state is getting send to the client. Therefor, it throws that warning that it is failing to serialize the store state, because it stores class instances (models).

I think, generally speaking, Vue, Vuex and Nuxt don't want to developer to store anything but serializable object to the store state – which is I think no Functions.

To avoid this, Vuex ORM must store pure object to the store (not class instance), and then re instantiate each records when we fetch through getters. This was what it was few month ago with Vuex ORM. I've changed it to get a bit more performance boost, and also to implement index mapping.

Maybe we should go back to old days...? Or maybe we could wait until Vuex 3 comes out (and hopefully Vuex 4), to see what is the right way to go. I guess we need more discussion on this topic.

**Comment by willhoyle** [comment]
If anyone coming across this wants to get rid of the warning you can change either one of the following env vars on the server:
```js
process.env.NUXT_ENV_DEVALUE_LOG_LEVEL = 'silent' // default is 'warn'
// or
process.env.NUXT_ENV_DEVALUE_LOG_LIMIT = 0 // default is 99
```

Check a list of log levels here for consola: https://github.com/nuxt/consola/blob/master/src/types.js

Here is the discussion on nuxt.js issue board: https://github.com/nuxt/nuxt.js/issues/4026

Note I believe you need nuxt version >=2.2.0

**Comment by ozum** [comment]
@willhoyle Doesn't it suppress all log messages then?

BTW, I didn't know this option thanks for the suggestion.

**Comment by willhoyle** [comment]
I believe it only suppresses the logs from the devalue lib. 

It’s actually weird behaviour that it logs stuff by default unless I’m missing something here.

**Comment by kiaking** [comment]
Wow, thanks for the tip! This is gonna clean up my terminal log quite a bit.

I guess it's expected for Nuct to output this warning. Before it was error and service were crashed (Good thing it became warning).

Still not sure how to handle this problem. I'm thinking for a while but, maybe we should make Store state POJP (plain old JavaScript Object). But not sure.

**Comment by willhoyle** [comment]
It seems like the problem in the devalue lib is that it's checking for a toJSON method. 

I was able to completely get rid of the warnings by making a plugin to modify the Model.

```js
const plugin = {
  install(components) {

    components.Model.prototype.toJSON = function () {
      return this.$toJson()
    }

  }
}
```

Would it make sense to make this toJSON method included in vuex-orm instead of a plugin?

**Comment by kiaking** [comment]
Oh wait what!? Really? If this is going to fix the problem, I think it definitely should go in to the Core.

But I couldn't find a source where devalue is checking `toJSON` method. Could you guide me to the code? I just want make sure if this will not break anything 🤔

**Comment by ozum** [comment]
> It seems like the problem in the devalue lib is that it's checking for a toJSON method.

@kiaking, that would be a nice solution to this problem

**Comment by willhoyle** [comment]
Yup it's here: https://github.com/nuxt/devalue/blob/5f2c22949fc8e41d60c84be36a6603809e821b59/src/index.ts#L134

**Comment by kiaking** [comment]
@willhoyle AHHHH NIIIICE! Very cool! This is the Nuxt forked version of devalue hah. Sorry I was looking at original devalue package.

I think adding toJSON method to the model is good! One concern is that maybe the Nuxt will change this behavior in the future but even if they did, toJSON method will do nothing for Vuex ORM users anyway.

Wonderful! Thank you so much @willhoyle for finding this! Would you like to make PR for this? Or I would just make one.

**Comment by willhoyle** [comment]
I'm a bit busy with work right now so I won't be able to do it until the weekend but go ahead if you don't mind! 

I think adding the method wouldn't break anything since if the user defined a toJSON method in their model, it would just overwrite the internal toJSON method anyways.

**Comment by kiaking** [comment]
@willhoyle Got ya! I'll create PR for this and make a release soon. Thank you so so so much for finding out the solution for this! ❤️

**Comment by willhoyle** [comment]
No problem! It’s the least I could do considering all the great work you’ve done on this lib!

**Comment by kiaking** [comment]
Done! This is fixed at Vuex ORM 0.31.3 🎉 
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.31.3

Again, thank you @ozum and @willhoyle for finding the solution for this! 👍

**Comment by ozum** [comment]
Thanks @willhoyle

**Comment by brfrth** [comment]
@kiaking @willhoyle Has this regressed? Missing the toJSON on the model and getting the error. Seems the current version is lacking this change.

**Comment by willhoyle** [comment]
Just quickly looked at this, we added the toJSON function to models on version v0.31.3: https://github.com/vuex-orm/vuex-orm/blob/v0.31.3/src/model/Model.ts (search for toJSON, it's at the bottom)

The latest release does not have this function anymore. I'm not sure at what point it was removed. Maybe there's a specific reason it was removed. I'd have to clone the repo and properly search the git history.

We should probably add it back in?

**Comment by eyesurewould** [comment]
> We should probably add it back in?
Yes please!

**Comment by cuebit** [comment]
@brfrth @willhoyle @eyesurewould any chance of a reproducible repo or link?

I can spin up nuxt with Vuex ORM 0.36 without issue. Note, Vuex ORM no longer stores instances, and only POJO, in Vuex so serializing shouldn’t be an issue here.

**Comment by drewbaker** [comment]
Getting this error today with `"vuex": "^3.6.0" and "@vuex-orm/core": "^0.36.3",`

**Comment by alexcroox** [comment]
I too am getting this with the latest few versions of Nuxt

**Comment by x-N0** [comment]
Working with Nuxt content module, had this issue.

**Comment by avillapalos** [comment]
Maybe this can help someone:

I solved the problem converting the class object to a POJO's at `toJSON()` function (which is the function `devalue` library calls). So an example would be:

```
class User {
  toJSON () {
    return { ...this } // here I make a POJO's copy of the class instance
  }
}
```
It's a clear solution which also makes sense to solve the warning.

**Comment by alizangiabadicode** [comment]
I am getting this error too

**Comment by oscarhandsome** [comment]
I tried the above suggestions but it didn't help. After adding into nuxt config file, resolved issue:
```
experimental: {
    renderJsonPayloads: false,
  },
```

**Comment by MahbodHastam** [comment]
> I tried the above suggestions but it didn't help. After adding into nuxt config file, resolved issue:
> 
> ```
> experimental: {
>     renderJsonPayloads: false,
>   },
> ```

It disables SSR.
