### ISSUE TITLE
How do I access models as in the examples?

### ISSUE THREAD

**Issue by ekosynth** [vuex-orm/vuex-orm#267]
When I try to run :
`const person = Person.query().whereId(1).get();`

I get "ReferenceError: Person is not defined"

Do I need to import something in my components to use this syntax?

**Comment by kiaking** [comment]
@ekosynth Yes! You have to import model.

```js
import Person from '../models/Person' // <- The path to the model.

export default {
  computed: {
    person () {
      return Person.query().whereId(1).get()
    }
  }
}
```

**Comment by ekosynth** [comment]
D'oh!, Thanks! 

May I suggest adding this to the documentation?

**Comment by kiaking** [comment]
Sure! That would be great 👍

**Comment by emahuni** [comment]
I think this should be added ASAP. The examples should specify filenames so that new users have an idea of where something is being done. Anyone new kinda has to figure out how to do this. I figured it out, but after a few hours of re-reading and experimenting with code, which isn't ideal. Some devs will just move on. This is an awesome lib and documentation matters.

PS: It'd easier for us to contribute if you put a link to each documentation page's github source. see Sails documentation page: https://sailsjs.com/documentation/concepts/models-and-orm/models
when you hover on the page there is edit page and at the bottom there is a link to correct or contribute to the page.

**Comment by kiaking** [comment]
@emahuni Thanks for the feedback! Yeah, the documentation matters.

> It'd easier for us to contribute if you put a link to each documentation page's github source.

That would be great! Not sure how to do that in [Vuepress](https://vuepress.vuejs.org), but if we there's a way, that would be very cool.
