### ISSUE TITLE
Loss of reactivity when using same entity as root and in retrieved relations

### ISSUE THREAD

**Issue by tvillaren** [vuex-orm/vuex-orm#284]
As discussed on Slack, here is the type of issue I'm trying to solve:

- I have a component with a Customer entity displaying fields like FirstName, LastName...
- I have a sub-component which takes as input an Address entity displaying other fields.
- My Customer entity has one Address (and vice-versa), linked by the CustomerId FK on Address.
- One of the Address component <span> visibility relies upon the `address.Customer.FirstName` field.
- When I change the `FirstName` on my "main component", so in the main entity, it does not impact my `customer.Address.Customer` entity (`customer.Address` is passed to the subcomponent and the "root" customer is loaded using `with('Address.Customer')` 

I loose reactivity because the 2 Customer instances are not the same JS object => when I change the root one, it doesn't change the one used in Address entity because they are 2 different 

Here is a JS fiddle which reproduces the issue: https://jsfiddle.net/vywknhsc/1/
When `FirstName === 'John'`, the "I want to be displayed reactively" message is displayed. This works on startup but when live-changing data.

Not sure what is the best solution to overcome this issue here. 

As of v0.31.2, I'm not sure if we get direct references to the store objects or not when using getters?
Might come from this (I don't get any Vuex State direct mutation console error in the JSFiddle which tends to let me think we clone data from the store and we can modify them directly, is it the case).

**Comment by kiaking** [comment]
OK, the first and the most, you should avoid setting the value returned from Vuex Getter.

At `mounted` hook in `customer-form` component, you are directly assigning query result, and you are trying to update the value with `v-model`. This is essentially the same as doing something like this.

```js
export default {
  data () {
    return {
      firstName: 'John',
      lastName: 'Doe' 
    }
  },

  computed: {
    fullName () {
      return this.firstName + ' ' + this.lastName
    }
  },

  methods: {
    updateName (value) {
      this.fullName = value
    }
  }
}
```

Since Vuex ORM is returning Object or Array of Object, technically you might able to modify the data. However, it's an anti-pattern to mutate the data you fetched from Vuex outside of the mutation handler.

So in your case, instead of using `v-model`, you should always make sure you update records by `update` method.

**Comment by tvillaren** [comment]
Thanks @kiaking for the answer and code on: https://jsfiddle.net/73yu4tpa/3/

Bottom line is:
* always use `computed` to display information
* always use `$update` (or any commit-related method) to update data

**Comment by kiaking** [comment]
Great it worked for you! 🎉
