### ISSUE TITLE
orderBy - null values sort ahead of defined values

### ISSUE THREAD

**Issue by yowzadave** [vuex-orm/vuex-orm#307]
Perhaps this is by design, but it seems that sorting using `orderBy` sorts entities with null values _ahead_ of entities with defined values. This is not the way ActiveRecord works—in that case, any undefined value will sort after any defined value. Is there a way of using `orderBy` on a field that has some null values, and having the null values sort to the end?

**Comment by kkyouhei** [comment]
Hi @yowzadave 

Thank you for your report!
Maybe there is no way to solve the problem now...
```
User.all().sort( a, b => a.id > a.b )
```

But I'll be able to resolve this problem.

**Comment by kiaking** [comment]
@yowzadave Also mentioned in PR #316 but I've also confirmed that this is same for the lodash, so I would like to keep it as is at the moment.

I too understand that it seems bit wired because `null` is kinda ultimate 0 (the smallest). Also, I understand that we don't have to follow lodash spec, but since lodash is widely used library so I think it make enough sense to stick with it.

Thank you so much for the report. We can still rethink about this if we have more attention on this issue. 🤝

**Comment by yowzadave** [comment]
Thanks for the consideration—understand that there are differing opinions on the right way to handle this.
