### ISSUE TITLE
Design consideration

### ISSUE THREAD

**Issue by w4mike** [vuex-orm/vuex-orm#387]
Dear vuex-orm team,

I am just starting a new django/quasar/vuex-orm project, kind of ERP+CRM+...,
and I would like to make use of your vuex-orm project.

In the end I will have many many models (tables in the db) with many relations between them.

I am now wondering how to design the vuex-orm part:

Let's say I can later split my app into several GUI-Modules, but I will have overlapping data,
like Tags, which can be used in multiple of my GUI-Modules, or Users, which will be needed almost in every GUI-Module.

How will I now represent my database using vuex-orm ?

vuex-models: reflect the whole database as it is, or split into my GUI-Modules and thus redefine vuex-orm models ?

vuex-modules: basically same question in case I reflect the whole DB 1:1 in vuex-orm models:
create vuex-orm modules by GUI-Models in my app ? Or just globally reflect 1:1 the DB ?

vuex-orm stores: same here, assuming vuex-orm models and modules are reflecting my DB 1:1, split here ?

I would appreciate any comments on this design consideration.

Many thanks.

**Comment by tvillaren** [comment]
Hello @w4mike,

Vuex ORM is intended to be an abstraction layer to represent locally on the client the data model (a bit like [Entity-Relation](https://en.wikipedia.org/wiki/Entity%E2%80%93relationship_model) standard) with which you can interact from any UI component. 

I think it is better to use it as a real data model rather than a UI-module-model. On each UI component, you can decide what data to fetch from the server and how to fill the store with it, the underlying idea of the Vuex ORM library being to always have access to your data through the defined "entity-relation" model.

It is indeed advised to split your app in different GUI modules, all using the same model underlying. If you have some GUI-specific data, you can always decide to handle it separately through direct fetching and local handling of data (keeping in mind that you an only have one Vuex ORM store per app currently I believe) or integrate them in your Vuex ORM model. 

Hope this helps. Don't hesitate to join us on the [Slack channel](https://join.slack.com/t/vuex-orm/shared_invite/enQtNDQ0NjE3NTgyOTY2LTI0YjE5YmNmMDIxNWZlNmJhM2EyMDg1MDRkODA4YmQwMDU5OWRkZmNhN2RmOTZkZGZkODQxZTRkYjhmYmJiNTY) if you have more questions.

**Comment by kiaking** [comment]
@w4mike Hi! Do you have any progress on this issue? Just checking in here.

**Comment by w4mike** [comment]
Hello @tvillaren,

many thanks for your prompt reply.

@kiaking 
I started to implement first models as suggested in one orm.
Now I need to do some testing and build my basic building blocks, I am using quasar.
Later I guess I will write some codegen to automate transscription from Django to vuex-orm.
Currently trying to get the Store connected in quasar.

**Comment by kiaking** [comment]
@w4mike Great! thank you for the update! Do you want this issue to be open for another week or two? Or we could close it for now, and you could open another issue if you have anything. : )

**Comment by w4mike** [comment]
Many thanks, we can close this issue I think. Will open another one for other topics.
