### ISSUE TITLE
Having http plugin – REST API backend support

### ISSUE THREAD

**Issue by VRuzhentsov** [vuex-orm/vuex-orm#44]
Hi. Is it have sense to merge functionality from this repo https://github.com/aarondfrancis/vue-model ?

I think it would be nice to extend the functionality of the orm, or should it be done in the form of a plug-in thanks to the 0.18 version?

Or, if it develop as a plug-in, it will turn into dependency hell

**Comment by cjcrawford** [comment]
I'm actually working on a http plugin now that provides similar functionality for populating entity data. The vue-model package is a great inspiration and a very nice package as a standalone solution when not using vuex.

A direct merge doesn't look like a good fit as there are a lot of overlapping functionality and vuex-orm is very specific to the vuex plugin lifecycle.

The customizable methods and computed properties is the same as vuex-orm but through the store modules in vuex from actions and getters.

I think a simple http plugin would provide enough magic for xhr interaction between vuex-orm and api resources.

I will try to align the plugin methods with those of vue-model since the author has done a great job of laying the groundwork.

I absolutely agree that resource management through vuex-orm would bring some much needed functionality. However api resources are so variable that providing an opinionated solution could bloat the core package. Hence the reason plugin integration was born in 0.15!

**Comment by kiaking** [comment]
I agree with @cjcrawford. It's very nice to have http resource feature working nicely with Vuex ORM, but I wouldn't want to build it into the core package for several reasons.

Mainly because it's hard to choose which http library to use. Should it be axios? superagent? or fetch polyfill? I think it would be nicer to have the plugin something like `vuex-orm-axios` to expand the functionality.

Also as @cjcrawford mentioned, it is going to be hard to directly pull in vue-model code to Vuex ORM because of the architecture difference. It's going to be much easier to implement the features from scratch.

However, we can get much inspiration from the vue-model. Things like apply option, or error handling look really neet.

It would be cool if user could just do something like;

```js
// Lets say the plugin adds save action to dispatch a http request which will
// call PUT or PATCH request to the server.
store.$dispatch('entities/users/save', {
  apply: false // Do not save response data to Vuex ORM.
})
```

Anyway, if @cjcrawford can start with the base of the plugin (thank you so much for that by the way!), we could continue discussing this on that repo.

**Comment by VRuzhentsov** [comment]
@cjcrawford I also see a great props from using vuex instead that `vue-model`, that wi can also install a lot of plugins, for example persistedState

I'll be happy to wait for this http plugin

By the way, maybe we should not close the task, maybe someone else will have ideas on this occasion

@kiaking
About choosing http library, we can try to check property `Vue.$http`, in case if developer already install some `vue-resource` or `axios`, and then try to find other libs

**Comment by kiaking** [comment]
Oh yes, we could check $http, but my point was that every http library has slightly different api which is not fully compatible with each other. If we build http resource feature on top of axios, I don't think it's going to be easy for user to switch it to the superagent. Then user have to use two http library on that project and it kinda pain especially when you have lots of configuration such as http header or CORS related thing.

It could be really cool if we can define interface at base http plugin of the vuex and create adopter for the axios or superagent, so that the user can choose what ever client they want. Obviously it's going to be too complicated at this though.

**Comment by kiaking** [comment]
I'll change the issue title to make it easier to identify that this issue is about having api backend support!

**Comment by phortx** [comment]
Hi @kiaking ! Very nice project, thank you for your amazing work! :)

I have to quickly integrate our backend HTTP API (GraphQL via Vue-Apollo) to Vuex-ORM. Can you give me any advice how you would make that? Are there any hooks I can use or can I just overwrite some methods?

If I understand how to implement that, I would publish a vuex-orm-apollo plugin after I have a working implementation.

Thank you in advance for any advice :)

**Comment by kiaking** [comment]
Hi @phortx, thank you for the kind word 😃 

I'm not familiar with vue-apollo (nor GraphQL), so it's a bit hard for me to give you the best answer, but I think overriding modules actions and getter is the way to go (or create dedicated getters or actions).

So you're right about extending `subActions.ts`! However, Regarding plugin, modules are not exposed to `components` argument right now. Why? Because no one needed it until now, so I can make them exposed.

Since I don't know how to use apollo, I'll make an example of axios integration that might look similar to your needs.

```js
// Define plugin.
const plugin = {
  install ({ subActions }) {
    // Add new action that fetch data from backend and save to ORM.
    subActions.fetch = async ({ dispatch }) => {
      const res = await axios.post('...')

      dispatch('create', { data: res.data })
    }
  }
}

// Then user can use that actions like this.
store.dispatch('entities/users/fetch')
```

If you can send me some example code you're trying to make as a plugin, maybe I can give you more deep advice or idea! And thank you for thinking about creating plugin! I'll do my best to support it!

**Comment by phortx** [comment]
Good Morning (at least in germany)!

Thank you, @kiaking for the quick and useful answer.

Basically, GraphQL no magic. It just defines a API by accepting POST requests with JSON payload. In the JSON you define what data you want to have and you get a similar looking json with the data back. Pretty simple. There isn't a client library necessary at al basically. However apollo is a lib with some nice functionality and helps consuming a graphql api.

Basically what I want to have is a ORM, VUEX and Apollo. As you already discovered, I opened a GitHub Repo for that and I want to push something useful ASAP to that. I hope I can meet the requirements of the community 😅 

My current approach in my project (I'm not working on the plugin yet) differs somewhat from your suggestion. I'm acutally writing a Model base class, which adds convenience methods (like we're talking about in #60 ) and syncs the data between vuex and apollo. Here is the well working example of my `findAll()` method:

`data/model.js`:
```javascript
// I alias the Model base class from Vuex-ORM Mapper to inherit from it
import { Model as ORMModel } from '@vuex-orm/core';

// This is just my normal Vuex store, nothing special
import store from 'data/store';

// Apollo specific stuff
import apolloClient from 'data/apollo';
import gql from 'graphql-tag';

// Utils
import inflection from 'inflection';

/**
 * Syncs between our models, Vuex-ORM and the GraphQL API
 */
export default class Model extends ORMModel {
    // Cache the singular name of the entity
    private static singularEntityCached = null;

    // Helper method to get the singular form of the entity name
    private static singularEntity() {
        if (this.singularEntityCached) return this.singularEntityCached;

        this.singularEntityCached = inflection.singularize(this.entity)
        return this.singularEntityCached;
    }

    // Helper method, that saves data to the Vuex-ORM store
    private static _insert(data) {
        store.dispatch(`entities/${this.entity}/insert`, { data });
    }

    // This is where the magic happens
    public static async findAll() {
        // Fetch data from the GraphQL API
        // These queries are going to constants somewhere in the future to avoid duplications
        const response = await apolloClient.query({ query: gql`{ contract { id, name } }` });

        // Sync the data into the Vuex store via Vuex-ORM
        // TODO: Cleaning up the store before?
        this._insert(response.data[this.singularEntity()]);

        // Retrieve the new data from the Vuex-ORM store
        return store.getters[`entities/${this.entity}/all`]();
    }
}
```

And this is how I use it:

`data/model/user.js`:
```javascript
import Model from 'data/model';


export default class User extends Model {
    static entity = 'users';

    static fields () {
        return {
            id: this.attr(null),
            name: this.attr(''),
            email: this.attr(''),
        }
    }
}
```

and finally my component:
```
<template lang="pug">

    ul
          li(v-for="user in users" :key="user.name") {{user.name}}

</template>

<script>

    import User from 'data/model/user';

    export default {
        name: 'app',

        data() {
            return {
                users: []
            };
        },

        methods: {
            async fetchData() {
                this.users = await User.findAll();
            }
        },

        mounted () {
            this.fetchData();
        }
    }

</script>
```

I'm very interested in what you think about this approach. My goal is to keep the component code as  lean as possible and avoid any boilerplate. Also I want the component to don't care about where the data comes from (which an be different data sources in one app like local storage, graphql api, 3rd party API and so on) and could be exchangable.

**Comment by kiaking** [comment]
Thanks for your code! And yeah I'll be waiting for your plugin : )

Overall class definition and usage look fine by me, but, if it were me, I'd slightly change the implementation of `findAll`. If you assign users to `this.data` in your component like that, you will lose reactivity. Every time you update your Vuex Store, you must manually call `User.findAll()` inside your component.

If that is intended behavior, no problem, but generally, I think it's better to use computed property in your component to access Vuex Store.

So, for the model definition, I'll do like this.

```js
import { Model as ORMModel } from '@vuex-orm/core';
import store from 'data/store';
import apolloClient from 'data/apollo';
import gql from 'graphql-tag';
import inflection from 'inflection';

export default class Model extends ORMModel {
    private static singularEntityCached = null;

    private static singularEntity() {
        if (this.singularEntityCached) return this.singularEntityCached;

        this.singularEntityCached = inflection.singularize(this.entity)
        return this.singularEntityCached;
    }

    private static _insert(data) {
        store.dispatch(`entities/${this.entity}/insert`, { data });
    }

    // Add this method that only fetches data from ORM.
    public static findAll() {
        return store.getters[`entities/${this.entity}/all`]();
    }

    public static async fetchAll() {
        const response = await apolloClient.query({ query: gql`{ user { id, name } }` });

        this._insert(response.data[this.singularEntity()]);
    }
}
```

Then define your component like this.

```vue
<template lang="pug">
    ul
        li(v-for="user in users" :key="user.name") {{user.name}}
</template>

<script>
    import User from 'data/model/user';

    export default {
        name: 'app',

        computed: {
            users () {
                return User.findAll()
            }
        },

        mounted () {
            User.fetchAll();
        }
    }
</script>
```

This way, each time users in the store gets updated, the computed value `users` will also be updated automatically. 

The basic concept of Vuex is the Data Driven architecture. Instead of passing returned value from the method to the other place, you just update the store, and then let components update its value depending on the store state.

What do you think?

**Comment by phortx** [comment]
Reactivity is on my ToDo list. Thanks for your advice :)

I understand what you did there, but in this case, the component developer has to deal with the data source (fetching). I'd prefer a way in which everything works with a `User.findAll()` call. If that's not possible, then I'd fallback to this solution.

**Comment by kiaking** [comment]
> I understand what you did there, but in this case, the component developer has to deal with the data source (fetching).

Interesting. Maybe this is not your point, but would it be less awkward if you name the method something like `refresh` or `sync`? Because you know, if that component has child component that uses same state, the child component don't have to call `fetchAll`.

The parent component;

```vue
<template>
  <div>
    <UserList />
  </div>
</template>

<script>
import UserList from './UserList';

export default {
  name: 'app',

  components: {
    UserList
  },

  mounted () {
    User.fetchAll();
  }
}
</script>
```

Then in child (UserList) component;

```js
<template>
  <ul>
    <li v-for="user in users">{{ user.name }}</li>
  </ul>
</template>

<script>
import User from 'data/model/user';

export default {
  name: 'user-list',

  computed: {
    users () {
      return User.findAll();
    }
  }
  
  // No mounted method needed because the parent component will do that.
}
</script>
```

In this case, UserList component doesn't have to call `fetchAll`, or it shouldn't call `fetchAll`, because then you will fire request to the server twice. Well you can always add caching system so it might not be a problem :p Anyway, I would love to hear the result of your experiment! Looking forward to it.

**Comment by phortx** [comment]
I think, I'd pass the users as a prop into the child component. But let's assume we don't want to do that for `[enter reasons here]`. In this case I (as a random component developer :D) would expect `User.findAll()` to have some kind of caching (another point on my todo list), also I think apollo does some caching internally (therefore the in-memory-cache thingy).

In a (for me) perfect world I'd expect something like this:

- **Vuex:** Stores the global state just as it's supposed to do.
- **Vuex-ORM:** Manages the Vuex State and provides a nice Model API for working with the data.
- **Vuex-ORM-Apollo (or Vuex-ORM-REST, Vuex-ORM-*):** Makes sure the state is synced with the backend via the API, with caching and everything.
- **Vue Components:** Doesn't care about how data is managed "internally" (deduplication, caching, syncing, ...) just interact with the Model classes and instances via a simple API.

However, I think you've got a way better understanding of the whole Vue/Vuex topic then me. I'm rather new to the Vue world and never worked with Vuex (used js-data in my last project and not happy with it). And I'm just fiddling around with Apollo, Vuex-ORM and my GraphQL API :)

However if this setup (GraphQL + Vuex-ORM) works, I will replace my JS-Data + REST API Setup with it :)

**Comment by phortx** [comment]
> Only "find" is special because from the Vuex point of view, it is not "finding". It is actually inserting data to the state.

That's the point :)


> So I think this requires some kind of mind shift. Maybe, just maybe, fetchAll method should be called something like refresh, init, start or seed. What it does is it initializes the state.

I like the idea of dropping the CRUD mindset for a more practicable view. Thinking about that, I came to the conclusion that we basically have 2 layers: The model layer and the persistence layer.

On the model layer (which is used by the component developers) we care about getting models and working with them. That's the ORM part (this project) and we don't care where these data come from. We only do these three things with our data:

- Loading data (from global state into the local state): equals finding
- Persisting data (from local state to global state): quals saving (update, create)
- Deleting data (from local state and global state): equals destroying

Therefore following model methods come into my mind:

- `Model.load(filter)` param is optional. returns an array of model instances matching to the filter criteria (id maybe)
- `model.save()`
   - creating: `const user = new User({ name: 'somewhat' }); user.save()`
   - updating: `const user = User.find(42); user.name = 'Luke'; user.save()`
- `model.destroy()`

So we're loading data from the global state/store (getters in Vuex, `load()` in this example) and saving it back to the global state/store (mutations/actions in Vuex, `save()` in this example). I think the component developer shouldn't care about what happens behind the global state because it's out of his scope.

The other layer is the persistence layer, which's purpose is to sync the data between the global state and an arbitrary backend or even multiple backends. Due to the fact that these backends could be anything from a cookie to a database connection or API or whatever, I just call it the `persistence`. In my case this is a GraphQL API.

That means, that a plugin like vuex-orm-apollo acts on the persistence layer and should just hook into the global state management (Vuex / Vuex-ORM) and make sure, that the data is synced to one or multiple persistences by following these tasks:

- When `Model.load()` is called and data from the global state is requests, make sure all relevant data is available in the global state by loading it from the persistence.
- When `model.save()` is called and data is stored in the global state, make sure that the new data is also saved to the persistence.
- When `model.destroy()` is called and data is being deleted from the global state, make sure the data is also removed from the persistence.

There is already a database component in vuex-orm which seems to have no big purpose. Maybe this is the right place to hook persistence plugins into? Just a random idea.

I hope this makes my view on things understandable and helps to find a good way to add this kind of features (via plugins) to Vuex-ORM. I'm very eager to hear you opinion about this toughts :)

> That would be awesome! Please don't get me wrong about my opinions on this thread. I'm not trying to say your way of thinking is bad or wrong. I just want to share my full knowledge on this topic so you might figure out a nice solution from this discussion 👍

That's the goal and I really want to hear your opinion, because I want to understand and learn. And, well, it's your project :) Thank you very much for your time!

**Comment by kiaking** [comment]
I like the public API of the model (`load`, `save` and `destroy`). It's simple. I've thought many time on implement those, but couldn't figure out how to use them in the component while having reactivity work.

Let's make simple Vue Component as an example and see how it will change way we implement things. The following is the pure Vue Component without Vuex ORM and without backend integration.

```vue
<template>
  <div>
    <p>Name: <input v-model="name"></p>
    <p>Age: <input v-model="age"></p>

    <p>{{ name }} is {{ age }} years old.</p>
  </div>
</template>

<script>
export default {
  data () {
    return {
      name: '',
      age: 0
    }
  }
}
</script>
```

OK, this component can edit users name and age, and edited name and age will be displayed under the input field.

To do this using Vuex ORM, it becomes like this.

```vue
<template>
  <div>
    <p>Name: <input :value="user.name" @input="e => { update('name', e) }"></p>
    <p>Age: <input :value="user.age" @input="e => { update('age', e) }"></p>

    <p>{{ user.name }} is {{ user.age }} years old.</p>
  </div>
</template>

<script>
export default {
  data () {
    return {
      id: 1
    }
  },

  computed: {
    user () {
      return this.$store.getters['entities/users/find'](this.id)
    }
  },

  methods: {
    update (key, e) {
      this.$store.dispatch('entities/users/update', {
        id: this.id,
        [key]: e.target.value
      })
    }
  }
}
</script>
```

With this example, what would be like to use the model method? Let's think about `update`. You can't do `user.name = 'John'` because the `user` is computed property. Following your example, I think it is going to be like this.

```vue
<script>
import User from './models/User'

export default {
  data () {
    return {
      id: 1
    }
  },

  computed: {
    user () {
      return this.$store.getters['entities/users/find'](this.id)
    }
  },

  methods: {
    update (key, e) {
      const user = User.load(this.id)

      user[key] = e.target.value

      user.save()
    }
  }
}
</script>
```

Maybe not so bad? Next, how can we add `model.load()` in here? We can't do that inside computed property if the `model.load()` is async, so maybe assign it to data in created or mounted hook.

```vue
<script>
import User from './models/User'

export default {
  data () {
    return {
      user: {}
    }
  },

  created () {
    this.user = User.load(1)
  },

  methods: {
    update (key, e) {
      const user = User.load(this.id)

      user[key] = e.target.value

      user.save()
    }
  }
}
</script>
```

This looks almost as same as your first example. But now we lost reactivity. When user input data and update name or age, it wouldn't get displayed! So we must manually reassign data.

```vue
<script>
import User from './models/User'

export default {
  data () {
    return {
      user: {}
    }
  },

  created () {
    this.user = User.load(1)
  },

  methods: {
    update (key, e) {
      const user = User.load(this.user.id)

      user[key] = e.target.value

      user.save()

      this.data = user
    }
  }
}
</script>
```

Now it gets confusing. We are saving data to the Vuex ORM, but that saved data is not used in this component. We can remove `user.save()` method from above example and it will still work as it did before.

Plus, if we implemented things like this, if another component has references to the same user, that component will not be updated. If that component is the child component, then you can pass data as a porp, but sometimes your nonrelated component might want reference user data. For example at the top right corner of your UI, you might want to display user's name. And obviously, that component is not a child component of the example above so there's no way to pass props to that component.

Well, that's the reason we have Vuex. Vuex can create the global state so that many components can reference that state without having to pass props around.

So it looks like we need to use computed property. But we can't because the computed property doesn't allow async method. One idea is to use [this library](https://github.com/foxbenjaminfox/vue-async-computed). This plugin lets you define async computed property. It becomes like this.

```vue
<script>
import User from './models/User'

export default {
  data () {
    return {
      id: this.id
    }
  },

  asyncComputed: {
    async user () {
      await User.load(this.id)
    }
  },

  methods: {
    update (key, e) {
      const user = User.load(this.id)

      user[key] = e.target.value

      user.save()
    }
  }
}
</script>
```

Now we got back computed property! However, developers have to learn one more new special syntax `asyncComputed`. But maybe it worth it.

Is these example matches the way you wanted it to be? I would love to see your desired way of implementing above example.

Cheers 🍺

**Comment by phortx** [comment]
Wow. Thanks for the long answer!

For me this looks much more complicated than it should actually be. With my current JS-Data setup (and thats what I wish for Vuex-ORM) the example above would like this:

```vue
<template>
    <div>
        <p>Name: <input v-model="user.name" @input="user.save"></p>
        <p>Age: <input v-model="user.age" @input="user.save"></p>

        <p>{{ user.name }} is {{ user.age }} years old.</p>
    </div>
</template>

<script>
    export default {
        data () {
            return {
                user: User.find(2)
            }
        }
    }
</script>
```

I'd prefer to call `user.save()` on save-button click but for the sake of the example, we save it after the input changes.

What are the arguments against this example? (Maybe you already answered, but I don't get it, sorry) :)

The only issue I can imagine is that other components which are using the same model are not updated automatically. The solution for that is to have a eventHub and send a global `user updated` custom event.

**Comment by kiaking** [comment]
Hah, that could work if you are going to make another way to update other components by event hub that you mentioned.

> What are the arguments against this example? (Maybe you already answered, but I don't get it, sorry) :)

I think the biggest arguments from me is the reactivity issue, which you already mentioned as a downside where other components which are using the same model are not updated automatically.

If we can manage that through eventHub, maybe it could work well. However, not sure how to implement that. Because Vue Component has to subscribe to that eventHub in order to update Component state (`data`). Would it be something like this?

```js
<script>
    import User from './models/User'
    import EventHub from './EventHub'

    export default {
        data () {
            return {
                user: User.find(2)
            }
        },

        created () {
            EventHub.on('user.updated.2', () => {
                this.user = User.find(2)
            })
        }
    }
</script>
```

**Comment by phortx** [comment]
Yes that whats I thought of. Another solution would be if Vuex-ORM itself acts as a event hub and allows something like this:

```
       created () {
            this.user = User.find(2);
            this.user.$on('update', u => this.user = u);
        }
```

This leads me to the question: Could this complete built into the model? Each model instance could have an event listener and updates it's attributes and relations when an update happens? 🤔 

This is a kind-of reactivity because the other models only update when one model is `save()`d.

I'm not sure. Seems like this is a real brain twister ...

**Comment by kiaking** [comment]
Yea, it wouldn't be easy but possible I guess. But before going into details on how to implementing them, I think we must consider something.

If we are going implement EventHub so that multiple components can sync each other, then we wouldn't need Vuex. Because the main purpose of Vuex or Flux architecture is to do that "syncing". If we were to reimplement that feature by the different way, that is going to be some other library I guess. The global state can be just plain object. It doesn't have to be a Vuex store.

So the following example with event hub;

```vue
<script>
    import User from './models/User'
    import EventHub from './EventHub'

    export default {
        data () {
            return {
                user: User.find(2)
            }
        },

        created () {
            this.user = User.find(2);
            this.user.$on('update', u => this.user = u);
        }
    }
</script>
```

What it is doing is pretty much the same as following. 

```vue
<script>
    import User from './models/User'

    export default {
        computed: {
            user () {
                return User.find(2)
            }
        },

        methods: {
            update (value) {
                User.update(user.id, value)
            }
        }
    }
</script>
```

You wouldn't be able to do things like `user.save()` or `user.name = 'John'`, but that's the point of Flux. Why they wouldn't allow that kind of – in a way ordinally MVC approach – is intended.

Vue is more toward object-oriented than React and Redux, but it still takes pretty functional approach. So you wouldn't reassign the object you fetched (the user object), but instead, you update store and then component update itself by subscribing to the store. One way data flow.

I think it is same how Vue uses the props. You pass pros down to the component and the component which receives that props should not mutate the props directly. They should fire event; then the parent component does something about it. And that "event" is computed property and actions (mutations) instead of Event Hub in Vuex.

My conclusion is, that if we're going to use Vuex, we should stick to that Vuex architecture.

Does this make sense for you?

**Comment by phortx** [comment]
> What it is doing is pretty much the same as following.

Oh ... you're right. I highly admire you knowledge about Vue, Flux and everything around here.

> but that's the point of Flux

I think I'm still too MVC handicapped 🙄  I'm starting to change my mind how things with Flux work.

> My conclusion is, that if we're going to use Vuex, we should stick to that Vuex architecture.

Full ack! And everything makes sense of me. However I'm somewhat lost right now. After all what do you thing would be the best solution, the bast API for the component developer (aligned with Flux but with few effort for component devs as possible) and the best way to integrate a persistence synchronization (with REST or GraphQL etc)?

**Comment by kiaking** [comment]
Currently what I think it would be better (not best maybe) is let developer care if they want data to be persistent, or not. I think in many cases developers would want to care.

So Vuex Store (Vuex ORM) is kinda cache. If you save data into Vuex, it is not persistent. If you refresh the browser, it goes away.  And sometimes we want that! For example, many of my application need that feature. I would like to update Vuex Store so that other components update their displayed value, but don't want sync to the persistent layer (REST or GraphQL) just yet.

I want to persist data when a user actually clicks save button, then confirm button on the alert dialog. Then finally I want that data to be persistent in the real DB.

In such scenario, I think it is quite useful to have separate methods. For example,

- `user.make()` - Save data to the Vuex but not to the GraphQL.
- `user.create()` - Save to Vuex and GraphQL

Then developers can choose what they want to do with the data.

Same for the Git right? First, you add your change. But then you have to "commit" the change to take effect. Same mindset here.

If developers can think like that, then I think it will make sense for them to know that they first need to "sync" data between VuexORM and Backend. That is calling `sync` method in the `created` hook.

```vue
<template>
  <div>
    <p>Name: <input v-model="user.name"></p>

    <button @click="save">SAVE</button>
  </div>
</template>

<script>
export default {
  computed: {
    user () {
      return User.find(2)
    }
  },

  created () {
    // Initialize the component by syncing data between local and backend.
    User.sync()
  }
}
</script>
```

By the way, why this is so hard is because it's async. If fetching data from GraphQL could be synchronous, there's no problem at all. You don't need `User.sync()` method. Just hydrate data inside getters.

The only way to remove `User.sync()` method and make everything work with single `User.findAll()` I can think of, is to use [vue-async-computed](https://github.com/foxbenjaminfox/vue-async-computed) and `asyncComputed` property.

```vue
<script>
import User from './models/User'

export default {
  asyncComputed: {
    async user () {
      await User.find(2)
    }
  }
}
</script>
```

What do you think?

**Comment by phortx** [comment]
I think my brain hurts. However I like you're comparison to git.

The more I think about it, the more I feel it makes sense to decouple persistence and state, just like you said.

What about this (could be that this is the same as you suggest just other wording ;) )

```vue
<template>
  <!-- v-if to make sure the user is loaded -->
  <div v-if="user">
    <p>Name: <input v-model="user.name"></p>

    <!-- naming the method persist to make clear: this writes the stuff into the persistence
    <button @click="user.persist">SAVE</button>
  </div>
</template>

<script>
export default {
  data() {
     return { id: 42 };
  },
  computed: {
    user () {
      // Get the user from the store (as soon as it's there). If there is nothing in the store, it returns null
      return User.find(this.id);
    }
  },

  created() {
    // Fetch (or load or whatever you want to call it) the User from persistence into the store
    User.fetch(this.id);
  }
}
</script>
```

**Comment by kiaking** [comment]
Oh yeah, that's same as my example but yours is better in terms of error proofing : )

**Comment by phortx** [comment]
Alright, that sounds like we're on the same track now 🎉  :D 

I think the only part you have to change on Vuex-ORM are the convenience methods and to expose everything relevant to the Plugin API, document everything and then I (and others) can setup persistence plugins. Some kind of "How to write a persistence plugin" section in the documentation would be really awesome and would help a lot. Then I would start to work on vuex-orm-apollo (and may vuex-orm-rest too) :)

Or what do you think?

**Comment by kiaking** [comment]
> and to expose everything relevant to the Plugin API

Actually I did this yesterday. With Vuex ORM 0.16.3, you can override all modules to add new action, mutations and getters : )
https://vuex-orm.gitbooks.io/vuex-orm/plugins.html

For example, if you want to implement new `fetchAll` action via plugin, you can do this.

```js
const plugin = {
  install ({ subActions }) {
    actions.fetchAll = async ({ state, dispatch }) {
      // state.$name is the name of the entity defined in model for example `users`.
      const res = await axios.get(`/api/${state.$name}`)

      dispatch('create', { data: res.data })
    }
  }
}

// Now you can use that action.
store.dispatch('entities/users/fetchAll')
```

> Some kind of "How to write a persistence plugin" section in the documentation would be really awesome and would help a lot.

That's really a nice idea. We should. Let me add that to my list 🍺

**Comment by phortx** [comment]
> Actually I did this yesterday. With Vuex ORM 0.16.3, you can override all modules to add new action, mutations and getters : )

That was fast :D Thanks!

When do you think, you will you approach the model methods (`find()` and so on)?

**Comment by kiaking** [comment]
> When do you think, you will you approach the model methods (find() and so on)?

Not sure, I feel there maybe some edge case that might take awhile to solve. Or not. But it would be very nice if could start on working with creating actions and mutations and such. Because even though I've manage to create model method, you would still need to create actions and mutations and then call them inside model.

**Comment by phortx** [comment]
You're right. I'm asking because I'm working on a project for my company and I'd like to use Vuex-ORM, but if it's not ready (with apollo integration) soon, I can't use it :)

**Comment by kiaking** [comment]
Yeah, looking very much forward to see the plugin though, and as you know, I'm following your project ; )

**Comment by phortx** [comment]
I've pushed some basic proof of concept code into the vuex-orm-apollo repo now :) There's still a lot of work to do and quality to improve, but now we have something to talk about.

However, seems like the code example above doesn't work. See https://github.com/phortx/vuex-orm-apollo/blob/master/src/index.ts (`setupFetch()`).

When I call `store.getters[`entities/users/fetch`]()`, I get

```
__WEBPACK_IMPORTED_MODULE_1_data_store__.a.getters.entities/contracts/fetch is not a function
```

any idea?

Also I'm very happy about every suggestion, contribution or feedback to my code.

**Comment by kiaking** [comment]
@phortx Wow this is really cool! Thank you for your great work 🎉  

The reason why `store.getters['entities/users/fetch']()` is not working is because you're defining "actions" in `setupFetch()`. You need to define `getters` if you want it be accessible via getters.

If you're defining fetch as an action, then you should call it as `store.dispatch('entities/users/fetch')`.

**Comment by phortx** [comment]
Of course! Now I feel really stupid 🙈  :D 

Thank you, I will try to finish a prototype of the plugin tomorrow.

**Comment by phortx** [comment]
With `dispatch' it works. Thanks.

I need to access the model field definitions (to read the relations, properties etc). How can I achieve that? Before with my model base class I just did `this.fields()`, however within the plugin I can't find the model itself.

**Comment by phortx** [comment]
I solved this now by passing the database as option into the plugin, but that's not optimal I think.

**Comment by phortx** [comment]
Also I have a working proof of concept for reading data from a GraphQL API (saving is the next step)

https://github.com/phortx/vuex-orm-apollo

**Comment by kiaking** [comment]
Nice!!! Great work!

> I solved this now by passing the database as option into the plugin, but that's not optimal I think.

Yeah, for now, I think it's good to path database instance as an option. But I think I should prepare a cleaner way to access each model.

**Comment by rkingon** [comment]
in regards to the plugin code above:
```javascript
const plugin = {
  install ({ subActions }) {
    actions.fetchAll = async ({ state, dispatch }) {
      // state.$name is the name of the entity defined in model for example `users`.
      const res = await axios.get(`/api/${state.$name}`)

      dispatch('create', { data: res.data })
    }
  }
}

// Now you can use that action.
store.dispatch('entities/users/fetchAll')
```

I have a `static` property on the model: `endpoint` -- I would like to use this vs `state.$name` as the endpoint _could_ be different. how is this possible to get?

**Comment by rkingon** [comment]
ugh, of course right after posting, i try this and it works
```javascript
Query.getModel(state.$name)
```
I swear I tried that earlier...

**Comment by kiaking** [comment]
Nice! yes you can get Model class by that method : )

**Comment by kiaking** [comment]
Started new discussion at #200 so I'll be closing this one!
