### ISSUE TITLE
Many to many relation with additional field in pivot table?

### ISSUE THREAD

**Issue by pavel-mironchik** [vuex-orm/vuex-orm#527]
Hi. I don't see a way to set a value for an additional field in a pivot table, e.g. `type` in this example:

```
static fields() {
    return {
      roleId: this.attr(null),
      userId: this.attr(null),
      type: this.attr("")
    };
  }
```

I prepared a sandbox: https://codesandbox.io/s/vuex-orm-sample-application-8xbyg
The data structure is actually the same that Laravel returns when you use the `return $this->belongsToMany('App\User')->withPivot('type');` statement.

**Comment by moravecjakub** [comment]
Hello,

  I've tried to solve this by inserting main entities (e.g. user + roles) and then update pivot table with my own data. I suppose, that it should work when I manually create composed '$id' key.

But this not work, because composed '$id' key doesn't respect order of columns defined in pivot table model - e.g. primaryKey = ['role_id', 'user_id'] - they're reversed.

Ok, never mind, if they're reversed, so, I can create this '$id' key reversed too. But it is not work too, because 'update' action doesn't respect '$id' attribute -> looks for primary keys and compose them in right order => so, update method does not find data for update.

I think, there should be fixed order of composed columns in '$id' key in pivot table.

**Comment by pavel-mironchik** [comment]
Yeah, I stumbled upon "id" columns ordering in reverse when creating and vice versa when updating, too. This causes a duplication of entities, but it is another issue.

About my question, I even was naive enough to try `beforeCreate` lifecycle hook, but without a success :) A model in such a hook doesn't contain additional fields. 

Thanks for your participation, though.

**Comment by UncertaintyP** [comment]
@pavel-mironchik Can you install @vuex-orm/core from UncertaintyP/vuex-orm#insert-pivot-data and tell me if you run into any problems?

**Comment by kiaking** [comment]
This feature is now added to Vuex ORM 0.36.0 🎉 
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.36.0
