### ISSUE TITLE
Vuex ORM alongside existing Vuex state

### ISSUE THREAD

**Issue by alexsonnay** [vuex-orm/vuex-orm#541]
Is there a proper way to use Vuex ORM alongside an already existing Vuex state ?

If we already have a Vuex store, how would the database and the store be "mixed" regarding to an external API ?

**Comment by cuebit** [comment]
Not sure what exactly you’re asking. Can you provide a scenario to illustrate?

Vuex-ORM integrates with Vuex. It also allows for module nesting for independent model states. If you want communicate between different modules or states created outside Vuex-ORM you’ll want to bridge with some functionality because this library is not entirely isomorphic and doesn’t make assumptions about state management other than what it’s designed for.

**Comment by kiaking** [comment]
@alexsonnay Do you have any updates on this one 😃?

**Comment by kiaking** [comment]
Closing the issue due to inactivity. Though, I think it's answered. Please feel free to open another issue if there's anything 🤝
