### ISSUE TITLE
Update Normalizr

### ISSUE THREAD

**Issue by kiaking** [vuex-orm/vuex-orm#553]
Normalizr 3.5.0 is out but if we update, test fails. Haven't looked into it yet but we need to fix it.

**Comment by cuebit** [comment]
Looking at [this diff](https://github.com/paularmstrong/normalizr/commit/df459545714ecd3cfb4bafe0f7010a012b25f716#diff-0259e620a36a18bc8e8a06f1bf5b180d) it looks like `getId` is now called before the `processStrategy` hook rather than after. The current process mutates the input _after_ the id for the entity is collected so it has no effect.

Vuex ORM's current _ProcessStrategy_ simply generates the required id's so in theory it could be renamed to _IdAttribute_, provided as a closure for the `idAttribute` API and the `processStrategy` hook dropped altogether (and can be reinstated later if the input requires any additional mutation).

**Comment by cuebit** [comment]
This patch works with the new 3.6.0 release also.
