### ISSUE TITLE
Question: Computed/Getter in model definition ?

### ISSUE THREAD

**Issue by AlexandreBonaventure** [vuex-orm/vuex-orm#56]
Hi again,
Quickly, is there a way to define some computed/getter directly in model. Is it recommended to use es6 getters in Model class (I guess it will some have reactivity issue) ?

Use case : 
```
class User extends Model {
  static entity = 'users'

  static fields () {
    return {
      id: this.attr(null),
      firstname: this.attr(''),
      lastname: this.attr(''),
      computedName: this.computed(() => {
         return this.firstname +  ' ' + this.lastname
       })
    }
  }
}
```

**Comment by kiaking** [comment]
You can define any getter or method in the model class 😃 

```js
class User extends Model {
  static entity = 'users'

  static fields () {
    return {
      id: this.attr(null),
      firstname: this.attr(''),
      lastname: this.attr('')
    }
  }

  get fullName () {
    return this.firstname +  ' ' + this.lastname
  }

  addPrefix (prefix) {
    return prefix + ' ' + this.fullName
  }
}

const user = store.getters['entities/users/find'](1)

user.fullName // <- John Doe

user.addPrefix('Mr.') // <- Mr. John Doe
```

You won't have reactivity issue. If the state in the store gets updated, these getter or method also will be updated 👍

**Comment by AlexandreBonaventure** [comment]
Great, thanks!

**Comment by kiaking** [comment]
Glad to help! 🎉

**Comment by DoubleB123** [comment]
Hey @kiaking, sorry to resurrect an old issue, but I know normal vuex getters cache and only are rerun if the relevant state updates. Do you know if these getters have the same behavior?

**Comment by kiaking** [comment]
@DoubleB123 

**Short answer:**  
No, it will not cache the getters result.

**Long answer:**  
Vuex ORM uses pure Vuex getters, so it has **the same behavior** as Vuex. However, Vuex ORM uses getters as a function so that you can take arguments. In this case Vuex will not cache the result as stated [here at the documentation](https://vuex.vuejs.org/guide/getters.html#method-style-access).

Does this answer make sense to you?

**Comment by kiaking** [comment]
Currently, there's no way to fetch a single record directly via Vuex ORM API. Because all of the fetching is done by Query class.

However, since Vuex ORM is just a wrapper for the Vuex, you could access store state directly.

With your example, you could do something like this.

```js
computed: {
  userName() {
    return this.$store.state.entities.users.data[this.userId]
  },
  userFriends() {
    // You need to write your own logic to find the appropriate friends.
    return this.$store.state.entities.friends[this.userId]
  },
  friendList() {
    // do some heavy processsing here that involves this.userFriends
   return someValue;
  }
}
```

By doing this, you gain the caching mechanism of Vuex. It is going to be hard for Vuex ORM to handle these kinds of the case because the whole point of Vuex ORM is to be dynamic with fluent API, but being dynamic will make Vuex non-cachable.

Even though somehow if Vuex ORM could manage such use case, it is always going to be slower than writing your own logic. So I would like to recommend you to create your specific logic for a place where you need very heavy processing.

Anywhere else, you can use Vuex ORM query!

**Comment by DoubleB123** [comment]
Awesome, I appreciate the replies and all the work you've put into this!

**Comment by kiaking** [comment]
Thanks! Those are the words that make me soooo happy! ❤️
