### ISSUE TITLE
Data persistence with a backend

### ISSUE THREAD

**Issue by lewebsimple** [vuex-orm/vuex-orm#57]
Is data persistence possible with a backend (REST or other) ?

Thanks for such a great plugin!

**Comment by kiaking** [comment]
Hi! This issue is related to #44. Vuex ORM doesn't have specific feature to save data to the backend. Also, it will not be implemented to Vuex ORM core but there is a plan to create plugin to do that.

Having feature to save data to the backend is not that easy in terms of the design. For instance, what http library should we use? (axios, fetch, superagent?) or how should we design the endpoint (in module? in model?). What if we don't want use REST API?

That's being said, if you have any idea on how you would like to have public API on this feature, it would be great to share that idea on #44!

I'll close this issue due to the duplication, but please feel free to post your idea or thoughts on #44.
