### ISSUE TITLE
How to set default value from function only once?

### ISSUE THREAD

**Issue by DQvsRA** [vuex-orm/vuex-orm#584]
I have a model that generate UUID for user device, it then must be stored and never be changed. 

```
export default class ConfigModel extends Model {
  static entity = 'config'

  static fields () {
    return {
      appVersion: this.string(null),
      resolution: this.string(null),
      themeId: this.string(null),
      deviceId: this.string('', () => (function b (a) {
        console.log('Execute deviceId')
        return a ? (a ^ Math.random() * 16 >> a / 4).toString(16) : ([1e7] + -1e3 + -4e3 + -8e3 + -1e11).replace(/[018]/g, b)
      })())
}
}
```
Some parts of the model comes from external json and I use `vuex-orm-localforage` to store data locally:
```
await ConfigModel.$fetch()
if (!ConfigModel.exists()) {
  await ConfigModel.$create({ data: data })
}
```

As result I have `deviceId` function executed many times: 

<img width="180" alt="Screenshot 2020-03-04 at 10 02 50" src="https://user-images.githubusercontent.com/442111/75862510-5c9c1d00-5dff-11ea-9bc3-ac44ec5ca26d.png">

I think you might guess my question: Why so many calls and how can I make this scenario possible?

**Comment by Maqsyo** [comment]
This 'issue' has nothing todo with vuex-orm
What you are seeing here is recursion. 

![image](https://user-images.githubusercontent.com/19644698/75864271-0d0b2080-5e02-11ea-98f3-89c4e6dba4f6.png)

in my opinion it would be better to use the static "afterCreate" - method from your model class and generate a new deviceId if none is set

```
function b(a)
{
    console.log('Execute deviceId');
    return a ? (a ^ Math.random() * 16 >> a / 4).toString(16) : ([1e7] + -1e3 + -4e3 + -8e3 + -1e11).replace(/[018]/g, b);
}

export default class ConfigModel extends Model
{
    static entity = 'config'

    static fields()
    {
        return {
            appVersion: this.string(null),
            resolution: this.string(null),
            themeId: this.string(null),
            deviceId: this.string('')
        };
    }

    static afterCreate(model)
    {
        if (model.deviceId) { return; }
        model.deviceId = b('');
    }
}

```

**Comment by DQvsRA** [comment]
Oh, shit, you @Maqsyo right, it was late night yesterday. Thanks for advice, looks like it works as I wanted : )

I'm rewriting very old React and MMVC Haxe based application with complex data structures.
And I faced another kind of problem - the data come as one piece and I divided it into smaller Models :
```
export default class ManifestModel extends Model {
  static entity = 'manifest'

  static fields () {
    return {
      $type: this.string(null),
      settings: this.hasOne(ManifestSettingsModel, '$type', 'settings')
    }
  }
}
```
```
export default class ManifestSettingsModel extends Model {
  static entity = 'settings'

  static fields () {
    return {
      homeUrl: this.string(''),
      licenseProfile: this.string(''),
      licenseAcquisitionUrl: this.string(''),
      licenseAcquisitionErrorUrl: this.string(''),
      oAuth2AuthorizationPath: this.string(''),
      speedTestUrl: this.string(''),
      speedTestFileSize: this.number(null),
      speedTestBandwidthPercentage: this.number(null),
      productSuggestionsUrl: this.string(null),
      urlOverrideMap: this.attr([]),
      controlsTextUrl: this.string(null),
      themeId: this.string(null),
      parameters: this.hasMany(ManifestParameterModel, 'key', 'parameters')
    }
  }
}
```
```
export default class ManifestParameterModel extends Model {
  static entity = 'parameter'

  static fields () {
    return {
      key: this.string(null),
      value: this.string('')
    }
  }
}
```
And I registered it as 
```
database.register(ManifestModel)
database.register(ManifestSettingsModel)
database.register(ManifestParameterModel)
```

However after data has fetched with `vuex-orm-axios`, the structure looks kind of strange, with nulls:
![Screenshot 2020-03-04 at 13 19 47](https://user-images.githubusercontent.com/442111/75879405-ab57b000-5e1b-11ea-98c8-a85850e1d5bb.png)

I also would like to see this models organized in the same structure as data `manifest/settings/parameters`. How can I do that?

**Comment by cuebit** [comment]
> However after data has fetched with vuex-orm-axios, the structure looks kind of strange, with nulls:

You'll want to eager [load the relationships](https://vuex-orm.github.io/vuex-orm/guide/data/retrieving.html#relationships) in order for them to be populated. Otherwise their values will be empty arrays (for one-to many, many-to-many) or null (one-to-one).

If you'd like to load manifests with their settings, and settings with their parameters, you can do so with [loading nested relations](https://vuex-orm.github.io/vuex-orm/guide/data/retrieving.html#load-nested-relation):

```js
ManifestModel.query().with('settings.parameters').get()
// OR
ManifestModel.query().withAllRecursive().get()
```

**Comment by DQvsRA** [comment]
Thank you @cuebit for answer. 
Strange but for using `ManifestModel.query().withAllRecursive().get()` show me nothing in `settings` field:
```
[class_1]
0: class_1
$id: "$uid2"
$type: "manifest"
settings: null
__proto__: ManifestModel
length: 1
__proto__: Array(0)
```
And data displayed in vuex:
![Screenshot 2020-03-04 at 13 58 47](https://user-images.githubusercontent.com/442111/75881942-6b46fc00-5e20-11ea-86fe-516b13f5ca04.png)

**Comment by DQvsRA** [comment]
And this is a way how I retrieve the data: `ManifestModel.api().get(config.manifestUrl, { params: config.manifestParams })` with `vuex-orm-axios`

**Comment by cuebit** [comment]
@DQvsRA from what I can see, most likely your models and relations are not configured correctly.

Judging by the way you've defined your models, I'm assuming the following is what your request data should look like: 

```js
[
  {
    $type: "manifest1",
    settings: {
      [...],
      parameters: [
        {
          key: "key1",
          value: "setting1"
        }
      ]
    }
  }
]
```

All models must have a [primary key](https://vuex-orm.github.io/vuex-orm/guide/model/defining-models.html#primary-key) for relations to work. By default Vuex ORM looks for the field `id`. This could also be a [generated UID](https://vuex-orm.github.io/vuex-orm/guide/model/defining-models.html#uid-type). Since none of your models have a primary key, Vuex ORM cannot build the relations.

```js
$type: this.string(null),
settings: this.hasOne(ManifestSettingsModel, '$type', 'settings')
```

It's assumed `$type` is the primary key, in the absence of `id`, but you need to explicitly set the `primaryKey` on the model to tell Vuex ORM that is the case. The `hasOne` relation tells Vuex ORM you want to populate `ManifestSettingsModel` with data it finds with this key in your data input, and use `$type` as the foreign key, meaning this attribute name needs to exist on the `ManifestSettingsModel` model, but it's not. The `settings` argument also tells Vuex ORM that you want to use this field's value as the foreign key value to join the relation on, but it's a relation field so it won't work.

Without going down a rabbit hole and pointing out how the other models are misconfigured, I've created a [simple reproduction](https://codesandbox.io/s/elated-gauss-iu5tj) to point you in the right direction.

Hope this helps.
