### ISSUE TITLE
Are Triple Composite Keys Supported?

### ISSUE THREAD

**Issue by gradedcatfood** [vuex-orm/vuex-orm#600]
We have a laravel model that has a triple composite key as a pivot table. Currently, in our vuex orm model, we have the primary key as:

`static primaryKey = ['line_item_discount_id', 'orientation_id', 'orientation_type_id']`

But when data is inserted into the store we always get a duplicate record with the 3rd key with the value of null.

This screenshot shows that 2 records are being inserted even though our API is only delivering 1 record from that pivot table

<img width="502" alt="Screen Shot 2020-03-13 at 8 22 22 AM" src="https://user-images.githubusercontent.com/6394329/76634894-cdc88800-6503-11ea-8f88-d5354657bc9f.png">

Does Vuex ORM currently support 3 composite keys, or am I doing something wrong?

My current workaround is to not use 3 composite keys but instead just use a "normal" auto-incrementing id as the primary key. Which is not the end of the world but if I do that then I run into issues trying to access the new `pivot` attribute introduced in [v.36.0](https://github.com/vuex-orm/vuex-orm/releases/tag/v0.36.0). I have to specify the pivot model on the model with a custom attribute name, then access the data through that property name (something like this: https://github.com/vuex-orm/vuex-orm/issues/321#issuecomment-482040165)

Thank you!

**Comment by cuebit** [comment]
> Does Vuex ORM currently support 3 composite keys, or am I doing something wrong?

Yes, two or more composite primary keys are supported. Here's some [evidence](https://codesandbox.io/s/romantic-sound-6ymbk).

Could you elaborate by describing what your field setup looks like, any relations, etc?

**Comment by gradedcatfood** [comment]
Hi @cuebit, thank you very much for the fast response and helping out!

I removed many of the irrelevant basic fields in order to prevent this post from getting too large. Here are the 3 models involved with this relationship

Orientation.js
`
import { Model } from '@vuex-orm/core'
export default class Orientation extends Model {
    static entity = 'admin_orientations';

    static fields () {
        return {
            id: this.attr(null),
            name: this.attr(''),
        }
    }
}
`
LineItemDiscount.js
`
import { Model } from '@vuex-orm/core'
import Orientation from "./Orientation";
import LineItemDiscountOrientation from "./LineItemDiscountOrientation";

export default class LineItemDiscount extends Model {
    static entity = 'admin_line_item_discounts';

    static fields () {
        return {
            id: this.attr(null),
            name: this.attr(''),
            orientations: this.belongsToMany(
                Orientation,
                LineItemDiscountOrientation,
                'line_item_discount_id',
                'orientation_id'
            ),
        }
    }
}
`

LineItemDiscountOrientation.js
`
import {Model} from '@vuex-orm/core'

export default class LineItemDiscountOrientation extends Model {
    static entity = 'admin_line_item_discount_orientation';

    static primaryKey = ['line_item_discount_id', 'orientation_id', 'orientation_type_id']

    static fields() {
        return {
            line_item_discount_id: this.attr(null),
            orientation_id: this.attr(null),
            orientation_type_id: this.attr(null)
        }
    }
}
`

We don't have a model for the 3rd key, orientation_type (orientation_type_id) as there has been some discussion on wether or not this can just be a string vs a FK to a completely different table.

Now that I just typed that and thought about it. Is that what is causing the issue? We had a previous iteration that looked very similar but instead of `orientation_type_id` we just had `orientation_type` and it was a string. It looked something like this:

LineItemDiscountOrientation.js
`
import {Model} from '@vuex-orm/core'

export default class LineItemDiscountOrientation extends Model {
    static entity = 'admin_line_item_discount_orientation';

    static primaryKey = ['line_item_discount_id', 'orientation_id', 'orientation_type']

    static fields() {
        return {
            line_item_discount_id: this.attr(null),
            orientation_id: this.attr(null),
            orientation_type: this.attr('') // can be either "student" or "parent"
        }
    }
}
`

Thank you for your help on this

**Comment by cuebit** [comment]
> I removed many of the irrelevant basic fields in order to prevent this post from getting too large.

The more the merrier. So long as we have enough information to paint the picture and possibly reproduce, the better. Thank you for your detailed explanation and reflection.

> Is it possible to have a composite key, that one of its value is a string?

Yes. Either string or number are acceptable using `this.attr()`.

---

Could you provide an example of the data you're passing to a model for it to generate these records?

It goes without saying, when Vuex ORM normalizes the insertion data, for `LineItemDiscount` for example, it's going to create a pivot record in `LineItemDiscountOrientation` using `line_item_discount_id` and `orientation_id`. You can immediately see the issue here – there's no indication of the third key.

The only solution in this case is to insert the pivot records separately if you want to create indexes that respect the primary key composition.

That being said, if you feel your needs do not necessarily warrant a third key as you mentioned, you could insert `orientation_type ` into the pivot table and [access it](https://vuex-orm.github.io/vuex-orm/guide/model/relationships.html#access-intermediate-model) using the new feature in 0.36.0. Though, you mentioned you're facing some issues with this?

**Comment by gradedcatfood** [comment]
Thank you for the info. If we have the option to keep `orientation_type` a string, I have reverted LineItemDiscountOrientation.js to the following:

```
import {Model} from '@vuex-orm/core'

export default class LineItemDiscountOrientation extends Model {
    static entity = 'admin_line_item_discount_orientation';

    static primaryKey = ['line_item_discount_id', 'orientation_id', 'orientation_type']

    static fields() {
        return {
            line_item_discount_id: this.attr(null),
            orientation_id: this.attr(null),
            orientation_type: this.attr('')
        }
    }
}
```

We are using Vuex ORM Axios that calls the following:

`return LineItemDiscount.api().get('/api/line-item-discounts')`

which returns:
```
[
    {
        "id": 1,
        "name": "Low Income Discount",
        "amount": "1000.00",
        "total_available": 100,
        "created_at": null,
        "updated_at": null,
        "orientations": [
            {
                "id": 1,
                "name": "Orientation Name 1",
                "date_start": "2017-11-07 21:00:10",
                "date_end": "2017-11-08 21:00:10",
                "parent_orientation": 1,
                "price": "227.00",
                "waitlist": 1,
                "parent_date_start": "2017-11-07 21:00:10",
                "parent_date_end": "2017-11-08 21:00:10",
                "parent_price": "161.00",
                "parent_capacity": 50,
                "orientation_group_id": 1,
                "created_at": "2020-03-13 21:00:10",
                "updated_at": "2020-03-13 21:00:10",
                "deleted_at": null,
                "pivot": {
                    "line_item_discount_id": 1,
                    "orientation_id": 1,
                    "orientation_type": "student"
                }
            }
        ]
    }
]
```

When following this pattern (orientation_type as a string), I can access the pivot attribute with success. I just continue to run into an issue in my OG post where I get an duplicate record with `orientation_type` as null

<img width="502" alt="Screen Shot 2020-03-13 at 8 22 22 AM" src="https://user-images.githubusercontent.com/6394329/76634894-cdc88800-6503-11ea-8f88-d5354657bc9f.png">

**Comment by cuebit** [comment]
Thank you for providing the response data.

Unfortunately this is not possible to achieve in this manner. At least without introducing an additional relation which would require an additional model. You're therefore correct in assuming that this is not currently supported. 

The issue you are experiencing is admittedly unintentional behaviour caused by the existence of a third primary key and is a side effect when hot reloading or essentially where existing data is updated (because the axios plugin invokes `insertOrUpdate`). This may even be (albeit inadvertently) raised as a bug.

Alternatively, you are able to define a composite key on `Orientation` so your orientations are also based on primary key composition. I may be wrong and depends on your source of truth but this just illustrates a solution.

```js
class Orientation extends Model {
  static entity = 'admin_orientations'

  static primaryKey = ['id', 'type']

  static fields() {
    return {
      id: this.attr(null),
      type: this.attr(''), // "student" or "parent"
      name: this.attr('')
    }
  }
}
```

The intermediate model should compromise of the two primary keys that are defined by the `belongsToMany` relation. Any additional attributes are purely arbitrary and the new feature since 0.36.0 simply grants access to these.

```js
class LineItemDiscountOrientation extends Model {
  static entity = 'admin_line_item_discount_orientation'

  static primaryKey = ['line_item_discount_id', 'orientation_id']

  static fields() {
    return {
      line_item_discount_id: this.attr(null),
      orientation_id: this.attr(null)
    }
  }
}
```

Your data would need to reflect this:

```json
[
  {
    "id": 1,
    "name": "Low Income Discount",
    "orientations": [
      {
        "id": 1,
        "type": "student",
        "name": "Orientation Name 1"
      }
    ]
  }
]
```

I hope I'm understanding your goal.

**Comment by gradedcatfood** [comment]
Cue, thank you very much for your detailed response. I think you have outlined our goal very well and I thank you again for helping me and our team out with this question. I think we have enough to go off from here as i think adding "type" to orientation makes sense.

P.S. I love this package and appreciate you and everyone's hard work! This package makes working with complicated objects in Vuex SO much more manageable and friendly :)

**Comment by Tofandel** [comment]
Is there really no way to support triple primary key for a pivot table yet? This is a must have schema.. Having teams based roles my relationship is like this, but it just doesn't work, it will always save it with only 2 and other pivots are then lost
```
export default class RoleAdmin extends Model {
  // This is the name used as module name of the Vuex Store.
  static entity = 'role_admin'

  static primaryKey = ['role_id', 'user_id', 'site_id']

  // List of all fields (schema) of the post model. `this.attr` is used
  // for the generic field type. The argument is the default value.
  static fields() {
    return {
      role_id: this.attr(null),
      user_id: this.attr(null),
      site_id: this.attr(null),
    };
  }
}
```

**Comment by Tofandel** [comment]
#400
