### ISSUE TITLE
Updating related entity doesn't work

### ISSUE THREAD

**Issue by bestickley** [vuex-orm/vuex-orm#627]
#### Describe the bug

When I try and update a related entity with the primary key in the nested related object, the update doesn't work. Although, if I try and update with a related entity's foreign it works.

#### Steps to reproduce the bug

1. Define models [...]
```
class User extends Model {
  static entity = "users";
  static fields = {
    id: this.attr(null),
    organization: this.belongsTo(Organization, "organizationId",
    organizationId: this.attr(null),
  }
}
class Organization extends Model {
  static entity = "organizations";
  static fields = {
    id: this.attr(null),
    users: this.hasMany(User, "organizationId"),
  }
}
```
2. Create data [...]
```Organization.insert({ data: [{ id: 1 }, { id: 2 }] });
User.insert({ data: { id: 1, organizationId: 1 } });
User.update({ where: 1, data: { organization: { id: 2 } } }); // doesn't work
// User.update({ where: 1, data: { organizationId: 2 } }); //does work
```
3. Retrieve data [...]
```
const user = User.query().with("organization").where({ id: 1 }).first();
console.log(user.organization.id)
// should be 2 but is 1
```

#### Expected behaviour

`user.organization.id` should be 2 but it's 1

#### Versions

- Vuex ORM: 0.36.3
- Vue: 2.6.10

#### Link to minimal reproduction

If applicable, add a minimal demo link to help explain your problem. Some options for that are [CodePen](https://codepen.io/), [CodeSandbox](https://codesandbox.io/), [JS Bin](https://jsbin.com/) or [JSFiddle](https://jsfiddle.net/).

#### Additional context

Add any other context about the bug here.

**Comment by cuebit** [comment]
Thank you for opening this issue, @bestickley.

Unfortunately this is not a bug but intended behaviour. Updating relations requires a pragmatic approach, one that is often misunderstood and something we will continue to work on highlighting in the documentation.

Note, the following will not generate relations but will yield the relation criteria:

```js
User.insert({ data: { id: 1, organizationId: 1 } })
```

So, assuming your entities are populated as follows (or in a similar fashion):

```js
entities: {
  users: {
    1: { id: 1, organizationId: 1 }
  },
  organizations: {
    1: { id: 1 },
    2: { id: 2 }
  }
}
```

The following statement works, because you're instructing `User` to update data associated with the model:

```js
User.update({ where: 1, data: { organizationId: 2 } })
```

The following statement will not work, because you're instructing `User` to update data that is currently not associated with the model:

```js
User.update({ where: 1, data: { organization: { id: 2 } } })
```

Since you're not updating data directly on `User`, nor are you updating data for an existing relation, rather you are attempting to assign a new relation; there are two possible avenues you can take to accomplish this:

1. Mutate the foreign key on the target model (as you pointed out):
```js
User.update({ where: 1, data: { organizationId: 2 } })
```

2. Pass both target and source model data as a whole to allow normalization (this tells Vuex ORM to attach the relation key to the parent model):
```js
User.update({
  data: {
    id: 1,
    organization: { id: 2 }
  }
})
```

To conclude, use a `where` clause if your intention is to update existing data whether it's on the target or relation model. Omit `where` in the event you need to juggle relations.

Hope this provides enough insight into how relations are handled.

**Comment by bestickley** [comment]
@cuebit, excellent explanation. Thanks so much! I understand now.
