### ISSUE TITLE
Emit beforeSelect hook on find* methods

### ISSUE THREAD

**Issue by zorn-v** [vuex-orm/vuex-orm#633]
I'm try to write plugin to pouchdb. Currently I'm just use "changes" from beginning (since: 0) in pouchdb and insert all records to vuexorm. All works fine except browser very slowdown on many records when app loads. Now I want to implement load records on-demand (if it not found in vuexorm, try to load it from pouchdb) and via changes {since: 'now'}, but problem that find* methods did not emit beforeSelect hook.

Or maybe there is other method to extend find* methods ?

**Comment by kiaking** [comment]
Thanks for the report! Maybe this is the defect. We need to check. For the workaround, can you use:

```js
Model.query().where('id', 1).first()
```

Instead?

**Comment by cuebit** [comment]
@zorn-v The `beforeSelect` hook is exclusive to retrieving data that has a lookup criteria. Unfortunately the `find` method does not fall into this category because it is simply a key lookup (which doesn't adhere to any other lookup criteria).

As @kiaking mentioned, using `where` clauses will give you significant leverage over hook use.

N.B. Any performance issues in cases like this are incredibly difficult for us to assess and replicate, so the onus is on you and while we hope you can find any bottlenecks in your application, please don't hesitate to join the community on [Slack](https://join.slack.com/t/vuex-orm/shared_invite/enQtNDQ0NjE3NTgyOTY2LTc1YTI2N2FjMGRlNGNmMzBkMGZlMmYxOTgzYzkzZDM2OTQ3OGExZDRkN2FmMGQ1MGJlOWM1NjU0MmRiN2VhYzQ) if you'd like to discuss more details.

**Comment by zorn-v** [comment]
> For the workaround, can you use:

I know how to workaround in my project, but I want to share plugin to the public then.

**Comment by zorn-v** [comment]
Seems there is no need to insert entities on-demand. If use `pouchDb.allDocs` and insert them all at once instead using "changes since 0" and insert one by one on app load, there is no performance issues
