### ISSUE TITLE
Question - how to add custom model getters?

### ISSUE THREAD

**Issue by alexkopytov** [vuex-orm/vuex-orm#641]
Hi, sorry for disturbing but i didn't found anywhere how i could add additional getters to my model.
Issue that i tried to solve - i have backend Laravel app with server side pagination.
So i installed vuex-orm with axios-plugin and created BaseModel, where realized CRUD actions, which call Laravel app.
Like example index method in BaseModel:

```js
static apiConfig = {
  actions: {
    async index(params = null) {
      const response = await this.request({
        method: 'get',
        url: `${this.model.route}`,
        params: params,
        save: false
      })
      const { data, total, per_page, current_page } = response.response.data
      this.model.insert({
        data: data,
        meta: {
          total: total,
          per_page: per_page,
          current_page: current_page
        }
      })
    }
  }
}
```

So how i could get access to meta variable or any custom?
Or maybe there is some more clear solution for my problem?
Thx.

**Comment by cuebit** [comment]
Use [modules](https://vuex-orm.org/guide/digging-deeper/vuex-module.html#defining-modules) to compliment your model, or define [state](https://vuex-orm.org/guide/digging-deeper/vuex-module.html#defining-state) directly on your model. This is well(ish) documented.

For example, let's assume you have a User model:

```js
export class User extends Model {
  static entity = 'users'

  static fields() {
    return { ... }
  }
}
```

Add some initial state that will rest within your entity module, useful for your application to digest some defaults:

```js
static state() {
  return {
    total: 0,
    per_page: 10,
    current_page: 1
  }
}
```

Ditch the `apiConfig` definition in favour of [Custom Actions](https://vuex-orm.github.io/plugin-axios/guide/custom-actions.html) offered by the axios plugin, and commit meta data directly on the model itself:

```js
static async index(params) {
  const request = await this.api().get(this.route, { params, save: false })

  const { data, total, per_page, current_page } = request.response.data

  const entities = await this.insert({ data })

  await this.commit((state) => {
    state.total = total
    state.per_page = per_page
    state.current_page = current_page
  })

  return entities
}
```

Finally, add a useful method to get your meta data. A POJO is useful in this case since pagination requires all parameters:

```js
static getMetaData() {
  const { total, per_page, current_page } = this.store().state.entities[this.entity]
  return { total, per_page, current_page }
}
```

<details>
  <summary>Spoiler: The Entire Model</summary>
  
  ```js
  export class User extends Model {
    static entity = 'users'

    static route = '...'

    static fields() {
      return { ... }
    }

    static state() {
      return {
        total: 20,
        per_page: 10,
        current_page: 1
      }
    }

    static async index(params) {
      const request = await this.api().get(this.route, { params, save: false })

      const { data, total, per_page, current_page } = request.response.data

      const entities = await this.insert({ data })

      await this.commit((state) => {
        state.total = total
        state.per_page = per_page
        state.current_page = current_page
      })

      return entities
    }

    static getMetaData() {
      const { total, per_page, current_page } = this.store().state.entities[this.entity]
      return { total, per_page, current_page }
    }
  }
  ```
</details>

**Comment by alexkopytov** [comment]
Wow, much thx, you made my day.
Yeah, now i see that it is well documented. 
Proposal - mb will be useful add this example in axios-plugin doc, because SS-pagination it is really often case.

**Comment by kiaking** [comment]
Great to hear you made it 🙌  And yea this might be nice to be in the docs.
