### ISSUE TITLE
[Request Features] whereNull method

### ISSUE THREAD

**Issue by mean-cj** [vuex-orm/vuex-orm#650]
Hello 

How can find field value is null , or field not exists on documents
I think "whereNull" , whereNotNull this method is easy

Thank you.

**Comment by mean-cj** [comment]
Now we can use

```
      Model.query()
        .where((item) => {
          return  ( ! item.field ||  item.field  == null )
        })
```

**Comment by WoodyDark** [comment]
For now, if you just want to refactor the code, you can do so:
`Model.query().where('field', value => !value || value === null)`

This part of the [docs](https://vuex-orm.org/guide/data/retrieving.html#where-clauses) gives some extra examples

**Comment by cuebit** [comment]
As you and @WoodyDark have suggested, as a workaround, a suitable where clause is more efficient than introducing a new shorthand method for boolean-esque query modifiers. Doing so would also instigate an argument for other like-for-like methods such as `whereUndefined` or `whereFalse`, etc.

As a side note, `!value || value === null` will never reach the strict null check in the conditional because when `!value` is true or false, `value === null` will also be true or false respectively. So really all you need is `.where('field', (value) => !value)`
