### ISSUE TITLE
Performance issue, one array item update triggers all children components re-render

### ISSUE THREAD

**Issue by axe-me** [vuex-orm/vuex-orm#697]
#### Describe the bug

when use query result with v-for, any item in the list get updated will trigger all children components rerender. 

#### Steps to reproduce the bug

1. Define models 
2. Create data
3. Retrieve data 
4. Bind data to component as computed property 
5. Loop items with v-for, pass items to child component
6. update one of the item
7. all the children components get updated/re-rendered

#### Expected behaviour

Only the component with the updated item should be re-rendered.

#### Versions

- Vuex ORM: 0.36.3
- Vue: 2.6.11

#### Link to minimal reproduction

[CodeSandbox https://codesandbox.io/s/broken-https-l8mk8?file=/src/App.vue](https://codesandbox.io/s/broken-https-l8mk8?file=/src/App.vue)

#### Additional context

I tested with normal usage of vuex, has no this kind of issue. please check out the example in the code sandbox above.

**Comment by axe-me** [comment]
it also exists in the next version  
https://codesandbox.io/s/sharp-lichterman-5hwnq?file=/src/App.vue

**Comment by kiaking** [comment]
This is currently expected behavior. Your Vuex example is not equal to what Vuex ORM is doing.

The thing is, Vuex ORM returns new records from the store. Try changing your `list` computed property to this.

```js
const list = computed(() => {
  return store.state.list.map((item) => ({ ...item }));
});
```

Then you can see 2 update log is called. Vuex ORM must return a new object instead of returning the store state as is because we must "mutate" the state before returning it when we have relationships.

To resolve this issue, I think we need to implement a caching system in Vuex ORM.
