### ISSUE TITLE
Many to many orderBy pivot field

### ISSUE THREAD

**Issue by musixite** [vuex-orm/vuex-orm#723]
When using a many to many relationship with pivot fields, the orderBy doesn't work using the following syntax (where position is a number)

```
    collections() {
      return Collection.query()
        .with("pivot")
        .orderBy("pivot.position")
        .get();
    },
```

**Comment by cuebit** [comment]
`orderBy` is applied to the query runner, in your case it's Collection.

`orderBy("pivot.position")` will not work for two reasons:

1. Relations are loaded **after** the order is applied to the query.
2. Dot notation is not supported.

In order to sort by nested properties, you will need to run `sort(yourComparator)` on the resultset e.g. `Collection.query().with('pivot').get().sort(...)`

**Comment by musixite** [comment]
wonderful. thank you!
