### ISSUE TITLE
[Question] Is there a lifecycle hook to handle the end of bulk inserts/deletes?

### ISSUE THREAD

**Issue by ntma** [vuex-orm/vuex-orm#725]
Hi Vuex ORM team,

My team recently got a feature request that requires committing some metadata to the model state after inserting/deleting items. At the moment we are relying on the `afterCreate` and `afterDelete` lifecycle hooks for this purpose. Everything works as expected when inserting/deleting single items, but we are experiencing an hit on performance when performing bulk operations (caused by N commits where N is the length of the bulk).

Considering this, is there a way of catching an event/lifecycle hook that marks the end of a bulk insert/delete?

**Comment by cuebit** [comment]
Currently not. Though it could potentially be nice to have. Sadly it's not a feature that would be considered for this branch of Vuex ORM.

More often than not, you would run your logic after you run your batch command because you know it's a batch command. This is a general statement for the most common use case because Vuex ORM does not know or care whether you want to insert one or more records.

However, you can administer this by checking if the data type is an array and then proceed to await the completion of the asynchronous task, run hook execution that determines whether or not the model carries a particular hook (or use a shell), then execute said hook with a payload – finally return the data from the initial invocation.

Or simply mimic the tasks on a base model (which gets more complex for methods such as update due to the varying payload type) for example:

```js
class BaseModel extends Model {
  static async insert(payload) {
    const res = await super.insert(payload)

    Array.isArray(payload.data) && this.onBatchInsert(res)

    return res
  }
}

class User extends BaseModel {
  static onBatchInsert(payload) {
    // do something...
  }
}
```

All of which will give you some form of global control for convenience.

**Comment by ntma** [comment]
Oh... I was so focused on using the hooks that I totally ignored the fact that I could just extend the calls to add my own logic. That's a good suggestion @cuebit , I'll stick with it. Thanks!
