### ISSUE TITLE
Are Vuex ORM queries asynchornous?

### ISSUE THREAD

**Issue by Marchiuzzz** [vuex-orm/vuex-orm#737]
Whenever I run an update for Vuex orm models, my whole website freezes until it's done. I do have some of my computed properties based on those updated model queries...and whenever they try to recalculate, that's when the website hangs. Is it true that Vuex ORM is halting the main thread?

For example running this 
```
CollectionObjects.delete((record) => {
      return objects.includes(record.object_id) && record.collection_id === self.selectedCollection
  });
```
Causes the mentioned effect.

**Comment by cuebit** [comment]
Hard to say why your app is hanging and freezing. Need a repro to be certain of the cause. This wouldn't be the first issue you've created about this, and I don't think this snippet of code offers any insight.

That said, the `delete` method with closures are run on every item in the entity until each one is resolved subsequently triggering computed props to re-calculate. 

Javascript is single threaded, so it's unlikely Vuex ORM is the single cause of thread blocking. Any code evaluated is going to be on the main thread. That said, the most common cause of UI hang is the UI rendering itself. While computed properties aim to cache results, function returning getters are not cached at all (hence why Vue will re-calculate them — by design).

If you run the Profiler in devtools you'll be able to gauge better understanding of what's taking long to evaluate and how many times something is executed. I would start here.

**Comment by cuebit** [comment]
To answer this issues question in the title, no, queries are not asynchronous. However, persist methods are, including `delete`. 

If you find anything upon further investigation, don’t hesitate to open another issue 👍
