### ISSUE TITLE
Implement lifecycle hook – Subscribe to insert/update with relationships

### ISSUE THREAD

**Issue by AlexandreBonaventure** [vuex-orm/vuex-orm#83]
Hello, 

For my use-case, I want to be able to subscribe to any changes that happens to a model (created/deleted/updated instances). It works fine with `store.subscribe` vuex API, but vuex-orm does not fire relationship mutations when inserted from their parent relationships for instance (which is not an issue by the way).

```js
class User extends Model {
  static fields () {
    return {
      id: this.attr(null),
      bookCurrentlyReading: this.belongsTo(Book, 'currentBookId')
    }
  }
}

class Book extends Model {
  static fields () {
    return {
      id: this.attr(null),
    }
  }
}
```

You see, if I insert this data 
```js
dispatch('entities/user/insert', {
  id: 1, 
  bookCurrentlyReading: {
    id: 12, 
    title: 'a Book'
  }
})
```

I want to be able to subscribe to inserting/updating actions that happen to book model only. 
No mutation is fired for book model (eg: 'entities/insert'  with `entity === 'book'` )
So now, I'm forced to subscribe to user model to retrieve data when a book change.

```js
store.subscribe(({ type, payload }, state) => {
  if (type === 'entities/insert' || type === 'entities/update') {
    const { entity } = payload
    if (entity === 'book') {
       //dont gets it
    } else if (entity === 'user') {
       //gets it
    }
  }
})
```

Would it be valuable to have an API for this. Is there any workaround you can suggest ?
Thanks

**Comment by kiaking** [comment]
Thanks for the feedback. Yeah this can be tough to catch via `store.subscribe` method. Maybe it depends on what you want to do when subscribing to the book model change, but I think it would be good for Vuex ORM to implement such lifecycle hook that users can subscribe to.

To do so, I'm thinking to add method that you can define on modules for example something like `onInsert` method.

Could you elaborate bit more on what you are trying to do after `entity === 'book'`? Maybe it depends on that use case on how or where to emit the lifecycle hook.

**Comment by AlexandreBonaventure** [comment]
Yes, I feel like adding lifecycle hooks to models definition could be a great feature. My need is mostly about tracking changes on models to fire some persisting cache/save some data in local database

**Comment by kiaking** [comment]
OK, thanks for the confirmation. I've been thinking about lifecycle hooks but not sure where to define it just yet if it should be in model or module (or maybe both). I'll think about it and try to come up with nice API 😃

**Comment by kiaking** [comment]
I was thinking about the implementation of the lifecycle hook event, and here I would like to share my thoughts. It might be harder than I thought.

Let's say we add `beforeCreate` and `afterCreate` hook. To define those hook, I think it's nice to be able to define both in modules (in action), and models.

```js
// Define hooks in the module action.
const actions = {
  // the `user` is the user object that has been created.
  afterCreate (context, user) {
    // ...
  }
}

// Define hooks in the model.
class User extends Model {
  // the `user` is the user object that has been created.
  beforeCreate (user) {
    // ...
  }
}
```

Now, it is easy to imagine that a user would like to dispatch another action in this `beforeCreate` method. For example, maybe user would like to increment a count field of a user when a new post is being created for that user.

With the current implementation of Vuex ORM, all of the operations happen inside mutation handler. This is because we're just calling `Query.create` method to dispatch all complicated logic inside Query class. Which means, by the time we know what records are being created, it's inside mutations handler.

The problem is we shouldn't be calling `dispatch` inside mutations handler since it could be async. So, maybe we should change how data is being saved to the state via Query class but haven't come up with any idea yet.

Maybe we should separate data normalization (preparation) phase and committing the normalized data phase. And call hooks inside the action. Or maybe it's hacky but pass action context to the Query class and let Query class commit each entity mutation...?

```js
// Something like below? Omitting many intermediate processes but I think it
// shows the idea.

create (context, { data }) {
  Query.create(rootState, state.$name, data, context)
}

class Query {
  static create (state, entity, data, context) {
    const normalizedData = this.normalize(data)

    Object.keys(normalizedData).forEach((entity) => {
      const record = normalizedData[entity]

      this.dispatchHook('beforeCreate', record)

      context.commit(`${state.$name}/${entity}/create`, { data: normalizedData[entity] })

      this.dispatchHook('afterCreate', record)
    })
  }
}
```

I haven't come to any conclusion but just wanted to open my mind. I'll come back again if I come up with anything solid.

**Comment by kiaking** [comment]
I've started this at #133. It works pretty well right now ❤️

**Comment by kiaking** [comment]
Lifecycle Hook is now supported by Vuex ORM 0.24.0! 🎉 
https://github.com/vuex-orm/vuex-orm/releases/tag/v0.24.0

I would like to make it able to define lifecycle hook at models too, but I'll create new issue for this.

**Comment by rkingon** [comment]
Sorry to bring this one back to life, but per the code above...

```js
// Something like below? Omitting many intermediate processes but I think it
// shows the idea.

create (context, { data }) {
  Query.create(rootState, state.$name, data, context)
}

class Query {
  static create (state, entity, data, context) {
    const normalizedData = this.normalize(data)

    Object.keys(normalizedData).forEach((entity) => {
      const record = normalizedData[entity]

      this.dispatchHook('beforeCreate', record)

      context.commit(`${state.$name}/${entity}/create`, { data: normalizedData[entity] })

      this.dispatchHook('afterCreate', record)
    })
  }
}
```

the hook only passes in the `record` -- which is normalized. sometimes it is also very handy to have the `payload`/`data` as well.. Can we pass this into the hooks as well?

**Comment by kiaking** [comment]
@rkingon Thank you for the feedback! Oh yeah that's so true. Could you create a issue for that? So that it gets a bit more attention 🤝
