### ISSUE TITLE
Updating relationships Bug ?

### ISSUE THREAD

**Issue by AlexandreBonaventure** [vuex-orm/vuex-orm#84]
Hi again,
https://codesandbox.io/s/1wvjq1jxw3

When defining inverse hasOne relationship. update fails to update relationship/ insert succeed.
Is that expected behaviour ?

**Comment by iNaD** [comment]
Hi,

the update method is currently under rework, because it misses a lot of functionality which is already implemented in some of the other actions.

One solution would be to use the newly introduced `insertOrUpdate` action, which handles relationships. I applied it to your sandbox code, so you can see it in action here: https://codesandbox.io/s/kw8662o643

**Comment by kiaking** [comment]
OK, this is actually the feature request, since I wasn't thinking of passing related records to `update method`. Currently `update` method only supports non nested relation data. I think it's nice to support this feature so we should!

However as a workaround as mentioned by @iNaD, I think you can use `insertOrUpdate` method to get what you want!

**Comment by kiaking** [comment]
This is now supported by Vuex ORM 0.24.0! Now you can pass object with relationship to the `update` method 🎉
